(function(){function g(a){throw a;}var i=void 0,j=!0,l=null,r=!1;function t(){return function(){}}function aa(a){return function(b){this[a]=b}}function u(a){return function(){return this[a]}}var x,y=this;function ba(a,b){var c=a.split("."),d=y;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&b!==i?d[e]=b:d=d[e]?d[e]:d[e]={}}function ca(){}function da(a){a.la=function(){return a.Db?a.Db:a.Db=new a}}
function ea(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function ga(a){var b=ea(a);return"array"==b||"object"==b&&"number"==typeof a.length}function A(a){return"string"==typeof a}function B(a){return"function"==ea(a)}function ha(a){var b=typeof a;return"object"==b&&a!=l||"function"==b}function ia(a){return a[ja]||(a[ja]=++ka)}var ja="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),ka=0;function la(a,b,c){return a.call.apply(a.bind,arguments)}
function ma(a,b,c){a||g(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function na(a,b,c){na=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?la:ma;return na.apply(l,arguments)}
function oa(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}}var pa=Date.now||function(){return+new Date};function C(a,b){function c(){}c.prototype=b.prototype;a.a=b.prototype;a.prototype=new c;a.prototype.constructor=a};function qa(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}function ra(a){if(!sa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ta,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(ua,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(va,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(wa,"&quot;"));return a}var ta=/&/g,ua=/</g,va=/>/g,wa=/\"/g,sa=/[&<>\"]/;var xa,ya,za,Aa,Ba;function Ca(){return y.navigator?y.navigator.userAgent:l}Ba=Aa=za=ya=xa=r;var Da;if(Da=Ca()){var Ea=y.navigator;xa=0==Da.indexOf("Opera");ya=!xa&&-1!=Da.indexOf("MSIE");Aa=(za=!xa&&-1!=Da.indexOf("WebKit"))&&-1!=Da.indexOf("Mobile");Ba=!xa&&!za&&"Gecko"==Ea.product}var D=xa,E=ya,F=Ba,H=za,Fa=Aa,Ga=y.navigator,Ha=-1!=(Ga&&Ga.platform||"").indexOf("Mac"),Ia;
a:{var Ja="",Ka;if(D&&y.opera)var La=y.opera.version,Ja="function"==typeof La?La():La;else if(F?Ka=/rv\:([^\);]+)(\)|;)/:E?Ka=/MSIE\s+([^\);]+)(\)|;)/:H&&(Ka=/WebKit\/(\S+)/),Ka)var Ma=Ka.exec(Ca()),Ja=Ma?Ma[1]:"";if(E){var Na,Oa=y.document;Na=Oa?Oa.documentMode:i;if(Na>parseFloat(Ja)){Ia=String(Na);break a}}Ia=Ja}var Pa={};
function I(a){var b;if(!(b=Pa[a])){b=0;for(var c=qa(String(Ia)).split("."),d=qa(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var h=c[f]||"",k=d[f]||"",m=RegExp("(\\d*)(\\D*)","g"),n=RegExp("(\\d*)(\\D*)","g");do{var s=m.exec(h)||["","",""],p=n.exec(k)||["","",""];if(0==s[0].length&&0==p[0].length)break;b=((0==s[1].length?0:parseInt(s[1],10))<(0==p[1].length?0:parseInt(p[1],10))?-1:(0==s[1].length?0:parseInt(s[1],10))>(0==p[1].length?0:parseInt(p[1],10))?1:0)||((0==s[2].length)<
(0==p[2].length)?-1:(0==s[2].length)>(0==p[2].length)?1:0)||(s[2]<p[2]?-1:s[2]>p[2]?1:0)}while(0==b)}b=Pa[a]=0<=b}return b}var Qa={};function Ra(a){return Qa[a]||(Qa[a]=E&&!!document.documentMode&&document.documentMode>=a)};function Sa(a,b){for(var c in a)b.call(i,a[c],c,a)}function Ta(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}var Ua="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Va(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ua.length;f++)c=Ua[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var J=Array.prototype,Wa=J.indexOf?function(a,b,c){return J.indexOf.call(a,b,c)}:function(a,b,c){c=c==l?0:0>c?Math.max(0,a.length+c):c;if(A(a))return!A(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},K=J.forEach?function(a,b,c){J.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=A(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Xa=J.filter?function(a,b,c){return J.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=A(a)?a.split(""):
a,k=0;k<d;k++)if(k in h){var m=h[k];b.call(c,m,k,a)&&(e[f++]=m)}return e},Ya=J.every?function(a,b,c){return J.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=A(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return r;return j};function Za(a,b){return 0<=Wa(a,b)}function $a(a,b){var c=Wa(a,b);0<=c&&J.splice.call(a,c,1)}function ab(a,b,c,d){J.splice.apply(a,bb(arguments,1))}function bb(a,b,c){return 2>=arguments.length?J.slice.call(a,b):J.slice.call(a,b,c)};var cb="StopIteration"in y?y.StopIteration:Error("StopIteration");function db(){}db.prototype.next=function(){g(cb)};db.prototype.Ka=function(){return this};function eb(a){if(a instanceof db)return a;if("function"==typeof a.Ka)return a.Ka(r);if(ga(a)){var b=0,c=new db;c.next=function(){for(;;){b>=a.length&&g(cb);if(b in a)return a[b++];b++}};return c}g(Error("Not implemented"))};function fb(a,b){this.L={};this.e=[];var c=arguments.length;if(1<c){c%2&&g(Error("Uneven number of arguments"));for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){if(a instanceof fb){c=gb(a);hb(a);for(var d=[],e=0;e<a.e.length;e++)d.push(a.L[a.e[e]])}else{var c=Ta(a),e=[],f=0;for(d in a)e[f++]=a[d];d=e}for(e=0;e<c.length;e++)this.set(c[e],d[e])}}x=fb.prototype;x.j=0;x.version_=0;function gb(a){hb(a);return a.e.concat()}
function hb(a){if(a.j!=a.e.length){for(var b=0,c=0;b<a.e.length;){var d=a.e[b];Object.prototype.hasOwnProperty.call(a.L,d)&&(a.e[c++]=d);b++}a.e.length=c}if(a.j!=a.e.length){for(var e={},c=b=0;b<a.e.length;)d=a.e[b],Object.prototype.hasOwnProperty.call(e,d)||(a.e[c++]=d,e[d]=1),b++;a.e.length=c}}x.get=function(a,b){return Object.prototype.hasOwnProperty.call(this.L,a)?this.L[a]:b};
x.set=function(a,b){Object.prototype.hasOwnProperty.call(this.L,a)||(this.j++,this.e.push(a),this.version_++);this.L[a]=b};x.Ka=function(a){hb(this);var b=0,c=this.e,d=this.L,e=this.version_,f=this,h=new db;h.next=function(){for(;;){e!=f.version_&&g(Error("The map has changed since the iterator was created"));b>=c.length&&g(cb);var h=c[b++];return a?h:d[h]}};return h};function ib(){this.D=r}ib.prototype.B=function(){this.D||(this.D=j,this.f())};ib.prototype.f=function(){this.$b&&jb.apply(l,this.$b);if(this.Ib)for(;this.Ib.length;)this.Ib.shift()()};function jb(a){for(var b=0,c=arguments.length;b<c;++b){var d=arguments[b];ga(d)?jb.apply(l,d):d&&"function"==typeof d.B&&d.B()}};function kb(a,b){this.D=r;this.qc=b;this.Pa=[];a>this.qc&&g(Error("[goog.structs.SimplePool] Initial cannot be greater than max"));for(var c=0;c<a;c++)this.Pa.push(this.ua())}C(kb,ib);x=kb.prototype;x.qb=l;x.tb=l;x.ua=function(){return this.qb?this.qb():{}};x.sb=function(a){if(this.tb)this.tb(a);else if(ha(a))if(B(a.B))a.B();else for(var b in a)delete a[b]};x.f=function(){kb.a.f.call(this);for(var a=this.Pa;a.length;)this.sb(a.pop());delete this.Pa};function lb(){this.wb=[];this.Jb=new fb;this.Bc=this.Cc=this.Dc=this.vc=0;this.Mb=new fb;this.Yb=this.Ac=0;this.ab=1;this.ac=new kb(0,4E3);this.ac.ua=function(){return new mb};this.wc=new kb(0,50);this.wc.ua=function(){return new nb};var a=this;this.Bb=new kb(0,2E3);this.Bb.ua=function(){return String(a.ab++)};this.Bb.sb=t();this.Gc=3}function nb(){this.Nb=this.time=this.count=0}
nb.prototype.toString=function(){var a=[];a.push(this.type," ",this.count," (",Math.round(10*this.time)/10," ms)");this.Nb&&a.push(" [VarAlloc = ",this.Nb,"]");return a.join("")};function mb(){}function ob(a,b,c,d){var e=[];-1==c?e.push("    "):e.push(qb(a.vb-c));e.push(" ",rb(a.vb-b));0==a.Oa?e.push(" Start        "):1==a.Oa?(e.push(" Done "),e.push(qb(a.Ic-a.startTime)," ms ")):e.push(" Comment      ");e.push(d,a);0<a.zc&&e.push("[VarAlloc ",a.zc,"] ");return e.join("")}
mb.prototype.toString=function(){return this.type==l?this.Xb:"["+this.type+"] "+this.Xb};
lb.prototype.toString=function(){for(var a=[],b=-1,c=[],d=0;d<this.wb.length;d++){var e=this.wb[d];1==e.Oa&&c.pop();a.push(" ",ob(e,this.vc,b,c.join("")));b=e.vb;a.push("\n");0==e.Oa&&c.push("|  ")}if(0!=this.Jb.j){var f=pa();a.push(" Unstopped timers:\n");d=this.Jb;b=function(b){a.push("  ",b," (",f-b.startTime," ms, started at ",rb(b.startTime),")\n")};if(ga(d))try{K(d,b,i)}catch(h){h!==cb&&g(h)}else{d=eb(d);try{for(;;)b.call(i,d.next())}catch(k){k!==cb&&g(k)}}}b=gb(this.Mb);for(d=0;d<b.length;d++)c=
this.Mb.get(b[d]),1<c.count&&a.push(" TOTAL ",c,"\n");a.push("Total tracers created ",this.Ac,"\n","Total comments created ",this.Yb,"\n","Overhead start: ",this.Dc," ms\n","Overhead end: ",this.Cc," ms\n","Overhead comment: ",this.Bc," ms\n");return a.join("")};function qb(a){var a=Math.round(a),b="";1E3>a&&(b=" ");100>a&&(b="  ");10>a&&(b="   ");return b+a}function rb(a){a=Math.round(a);return String(100+a/1E3%60).substring(1,3)+"."+String(1E3+a%1E3).substring(1,4)}new lb;function sb(a){this.context=a;this.inputBuffer=this.context.createGainNode();this.outputBuffer=this.context.createGainNode();this.Ma=[];this.G=[]}x=sb.prototype;x.connect=function(a){this.next=a;this.Ma=[].concat(this.inputBuffer,this.G,this.outputBuffer,this.next);this.s()};x.C=u("inputBuffer");x.ma=u("outputBuffer");x.$=aa("prev");x.s=function(){for(var a=this.Ma,b=0,c=a.length-1;b<c;b++)a[b].connect(a[b+1])};x.disconnect=function(){this.outputBuffer.disconnect()};function L(a){sb.call(this,a);this.X=this.context.createGainNode();this.G.push(this.X)}C(L,sb);L.prototype.Ga=function(a){a=Math.min(a,10);this.X.gain.value=a/10};L.prototype.s=function(){for(var a=this.Ma,b=0,c=a.length-1;b<c;b++)a[b].connect(a[b+1]);this.oa=[[this.G[0],this.inputBuffer,this.outputBuffer],[this.outputBuffer,this.G[this.G.length-1],l]]};function tb(a){L.call(this,a);this.ga=this.context.createConvolver();this.ob=this.context.createGainNode();this.G=[this.ga,this.ob];this.Xa()}C(tb,L);tb.prototype.Va="audio/ir/speaker/AK-SPKRS_VinUs_002.wav";tb.prototype.s=function(){tb.a.s.call(this);this.inputBuffer.connect(this.outputBuffer)};tb.prototype.Xa=function(){var a=this,b=new XMLHttpRequest;b.open("GET",this.Va,j);b.responseType="arraybuffer";b.onload=function(){a.context.decodeAudioData(b.response,function(b){a.ga.buffer=b})};b.send()};var ub={},vb=r,wb="click mouseover mouseout mousemove mousedown mouseup mouseenter mouseleave scroll".split(" ");
function xb(a){var b,c=b=a.target,d;do{if(!(d=ub[c.getAttribute&&c.getAttribute("data-cmp")]))(d=ub[c.id])&&b.setAttribute("data-cmp",c.id);if(d)break}while(c=c.parentNode);c=(b=d)&&b.H&&b.H[a.type];"mouseover"==a.type?a.relatedTarget&&!yb(a.target,a.relatedTarget)&&(d=new M(a.v),d.type="mouseenter",xb(d)):"mouseout"==a.type&&(a.relatedTarget&&!yb(a.target,a.relatedTarget))&&(d=new M(a.v),d.type="mouseleave",xb(d));if(c){d=Ta(c);do if("mouseenter"==a.type||"mouseleave"==a.type){if(a.relatedTarget&&
!yb(a.target,a.relatedTarget)&&zb(b,a,c,d)===r)break}else if(zb(b,a,c,d)===r)break;while((a.target=a.target.parentNode)&&a.target!=b.d())}}function zb(a,b,c,d){var e=j;K(d,function(d){0<=Wa(Ab(d),b.target)&&(e=c[d].call(a,b))});return e};var Bb,Cb=document.createElement("div");Bb=function(a){Cb.innerHTML=a;return Cb.removeChild(Cb.firstChild)};function Db(a,b){this.x=a!==i?a:0;this.y=b!==i?b:0}Db.prototype.toString=function(){return"("+this.x+", "+this.y+")"};var Eb;function Fb(a){a=a.className;return A(a)&&a.match(/\S+/g)||[]}function Gb(a,b){for(var c=Fb(a),d=bb(arguments,1),e=c.length+d.length,f=c,h=0;h<d.length;h++)Za(f,d[h])||f.push(d[h]);a.className=c.join(" ");return c.length==e}function Hb(a,b){var c=Fb(a),d=bb(arguments,1),e,f=d;e=Xa(c,function(a){return!Za(f,a)});a.className=e.join(" ");return e.length==c.length-d.length};var Ib=!E||Ra(9),Jb=!F&&!E||E&&Ra(9)||F&&I("1.9.1");E&&I("9");function Kb(a){return a?new Lb(Mb(a)):Eb||(Eb=new Lb)}var Nb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function yb(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}function Mb(a){return 9==a.nodeType?a:a.ownerDocument||a.document}function Ob(a){var b=a.getAttributeNode("tabindex");return b&&b.specified?(a=a.tabIndex,"number"==typeof a&&0<=a&&32768>a):r}function Lb(a){this.F=a||y.document||document}x=Lb.prototype;x.Qa=Kb;
x.d=function(a){return A(a)?this.F.getElementById(a):a};x.P=Lb.prototype.d;
x.u=function(a,b,c){var d=this.F,e=arguments,f=e[0],h=e[1];if(!Ib&&h&&(h.name||h.type)){f=["<",f];h.name&&f.push(' name="',ra(h.name),'"');if(h.type){f.push(' type="',ra(h.type),'"');var k={};Va(k,h);h=k}f.push(">");f=f.join("")}f=d.createElement(f);if(h)if(A(h))f.className=h;else if("array"==ea(h))Gb.apply(l,[f].concat(h));else{var m=f;Sa(h,function(a,b){"style"==b?m.style.cssText=a:"class"==b?m.className=a:"for"==b?m.htmlFor=a:b in Nb?m.setAttribute(Nb[b],a):0==b.lastIndexOf("aria-",0)||0==b.lastIndexOf("data-",
0)?m.setAttribute(b,a):m[b]=a})}if(2<e.length)for(var n=d,s=f,d=e,e=function(a){a&&s.appendChild(A(a)?n.createTextNode(a):a)},h=2;h<d.length;h++){var p=d[h];if(ga(p)&&!(ha(p)&&0<p.nodeType)){var k=K,q;a:{if((q=p)&&"number"==typeof q.length){if(ha(q)){q="function"==typeof q.item||"string"==typeof q.item;break a}if(B(q)){q="function"==typeof q.item;break a}}q=r}if(q)if(q=p.length,0<q){for(var z=Array(q),v=0;v<q;v++)z[v]=p[v];p=z}else p=[];k(p,e)}else e(p)}return f};x.createElement=function(a){return this.F.createElement(a)};
x.createTextNode=function(a){return this.F.createTextNode(a)};x.appendChild=function(a,b){a.appendChild(b)};x.wa=function(a){return Jb&&a.children!=i?a.children:Xa(a.childNodes,function(a){return 1==a.nodeType})};x.contains=yb;function Pb(a,b){var c;a:{c=Mb(a);if(c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,l))){c=c[b]||c.getPropertyValue(b)||"";break a}c=""}return c||(a.currentStyle?a.currentStyle[b]:l)||a.style&&a.style[b]}
function Qb(a){if(E&&!Ra(8))return a.offsetParent;for(var b=Mb(a),c=Pb(a,"position"),d="fixed"==c||"absolute"==c,a=a.parentNode;a&&a!=b;a=a.parentNode)if(c=Pb(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return l}
function Rb(a){var b,c=Mb(a),d=Pb(a,"position"),e=F&&c.getBoxObjectFor&&!a.getBoundingClientRect&&"absolute"==d&&(b=c.getBoxObjectFor(a))&&(0>b.screenX||0>b.screenY),f=new Db(0,0),h;b=c?Mb(c):document;if(h=E)if(h=!Ra(9))h="CSS1Compat"!=Kb(b).F.compatMode;h=h?b.body:b.documentElement;if(a==h)return f;a:{if(Fa&&H&&(b=a.ownerDocument.defaultView,b!=b.top)){b=r;break a}b=!!a.getBoundingClientRect}if(b)d=a.getBoundingClientRect(),E&&(a=a.ownerDocument,d.left-=a.documentElement.clientLeft+a.body.clientLeft,
d.top-=a.documentElement.clientTop+a.body.clientTop),b=d,a=Kb(c).F,c=!H&&"CSS1Compat"==a.compatMode?a.documentElement:a.body,a=a.parentWindow||a.defaultView,c=new Db(a.pageXOffset||c.scrollLeft,a.pageYOffset||c.scrollTop),f.x=b.left+c.x,f.y=b.top+c.y;else if(c.getBoxObjectFor&&!e)b=c.getBoxObjectFor(a),c=c.getBoxObjectFor(h),f.x=b.screenX-c.screenX,f.y=b.screenY-c.screenY;else{b=a;do{f.x+=b.offsetLeft;f.y+=b.offsetTop;b!=a&&(f.x+=b.clientLeft||0,f.y+=b.clientTop||0);if(H&&"fixed"==Pb(b,"position")){f.x+=
c.body.scrollLeft;f.y+=c.body.scrollTop;break}b=b.offsetParent}while(b&&b!=a);if(D||H&&"absolute"==d)f.y-=c.body.offsetTop;for(b=a;(b=Qb(b))&&b!=c.body&&b!=h;)if(f.x-=b.scrollLeft,!D||"TR"!=b.tagName)f.y-=b.scrollTop}return f}var Sb=F?"MozUserSelect":H?"WebkitUserSelect":l;function Tb(){}var Ub=0;x=Tb.prototype;x.key=0;x.Z=r;x.mb=r;x.na=function(a,b,c,d,e,f){B(a)?this.Eb=j:a&&a.handleEvent&&B(a.handleEvent)?this.Eb=r:g(Error("Invalid listener argument"));this.listener=a;this.proxy=b;this.src=c;this.type=d;this.capture=!!e;this.Ta=f;this.mb=r;this.key=++Ub;this.Z=r};x.handleEvent=function(a){return this.Eb?this.listener.call(this.Ta||this.src,a):this.listener.handleEvent.call(this.listener,a)};var Vb=!E||Ra(9),Wb=!E||Ra(9),Xb=E&&!I("8");!H||I("528");F&&I("1.9b")||E&&I("8")||D&&I("9.5")||H&&I("528");F&&!I("8")||E&&I("9");function Yb(a,b){this.type=a;this.currentTarget=this.target=b}x=Yb.prototype;x.f=t();x.B=t();x.M=r;x.defaultPrevented=r;x.Fa=j;x.stopPropagation=function(){this.M=j};x.preventDefault=function(){this.defaultPrevented=j;this.Fa=r};function Zb(a){Zb[" "](a);return a}Zb[" "]=ca;function M(a,b){a&&this.na(a,b)}C(M,Yb);var $b=[1,4,2];x=M.prototype;x.target=l;x.relatedTarget=l;x.offsetX=0;x.offsetY=0;x.clientX=0;x.clientY=0;x.screenX=0;x.screenY=0;x.button=0;x.keyCode=0;x.charCode=0;x.ctrlKey=r;x.altKey=r;x.shiftKey=r;x.metaKey=r;x.eb=r;x.v=l;
x.na=function(a,b){var c=this.type=a.type;Yb.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(F){var e;a:{try{Zb(d.nodeName);e=j;break a}catch(f){}e=r}e||(d=l)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=H||a.offsetX!==i?a.offsetX:a.layerX;this.offsetY=H||a.offsetY!==i?a.offsetY:a.layerY;this.clientX=a.clientX!==i?a.clientX:a.pageX;this.clientY=a.clientY!==i?a.clientY:a.pageY;this.screenX=a.screenX||
0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.eb=Ha?a.metaKey:a.ctrlKey;this.state=a.state;this.v=a;a.defaultPrevented&&this.preventDefault();delete this.M};function ac(a){return Vb?0==a.v.button:"click"==a.type?j:!!(a.v.button&$b[0])}
x.stopPropagation=function(){M.a.stopPropagation.call(this);this.v.stopPropagation?this.v.stopPropagation():this.v.cancelBubble=j};x.preventDefault=function(){M.a.preventDefault.call(this);var a=this.v;if(a.preventDefault)a.preventDefault();else if(a.returnValue=r,Xb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};x.f=t();var bc={},N={},O={},cc={};
function P(a,b,c,d,e){if(b){if("array"==ea(b)){for(var f=0;f<b.length;f++)P(a,b[f],c,d,e);return l}var d=!!d,h=N;b in h||(h[b]={j:0,q:0});h=h[b];d in h||(h[d]={j:0,q:0},h.j++);var h=h[d],k=ia(a),m;h.q++;if(h[k]){m=h[k];for(f=0;f<m.length;f++)if(h=m[f],h.listener==c&&h.Ta==e){if(h.Z)break;return m[f].key}}else m=h[k]=[],h.j++;var n=dc,s=Wb?function(a){return n.call(s.src,s.key,a)}:function(a){a=n.call(s.src,s.key,a);if(!a)return a},f=s;f.src=a;h=new Tb;h.na(c,f,a,b,d,e);c=h.key;f.key=c;m.push(h);bc[c]=
h;O[k]||(O[k]=[]);O[k].push(h);a.addEventListener?(a==y||!a.rb)&&a.addEventListener(b,f,d):a.attachEvent(b in cc?cc[b]:cc[b]="on"+b,f);return c}g(Error("Invalid event type"))}function ec(a,b,c,d,e){if("array"==ea(b))for(var f=0;f<b.length;f++)ec(a,b[f],c,d,e);else{d=!!d;a:{f=N;if(b in f&&(f=f[b],d in f&&(f=f[d],a=ia(a),f[a]))){a=f[a];break a}a=l}if(a)for(f=0;f<a.length;f++)if(a[f].listener==c&&a[f].capture==d&&a[f].Ta==e){Q(a[f].key);break}}}
function Q(a){if(!bc[a])return r;var b=bc[a];if(b.Z)return r;var c=b.src,d=b.type,e=b.proxy,f=b.capture;c.removeEventListener?(c==y||!c.rb)&&c.removeEventListener(d,e,f):c.detachEvent&&c.detachEvent(d in cc?cc[d]:cc[d]="on"+d,e);c=ia(c);O[c]&&(e=O[c],$a(e,b),0==e.length&&delete O[c]);b.Z=j;if(b=N[d][f][c])b.Gb=j,fc(d,f,c,b);delete bc[a];return j}
function fc(a,b,c,d){if(!d.za&&d.Gb){for(var e=0,f=0;e<d.length;e++)d[e].Z?d[e].proxy.src=l:(e!=f&&(d[f]=d[e]),f++);d.length=f;d.Gb=r;0==f&&(delete N[a][b][c],N[a][b].j--,0==N[a][b].j&&(delete N[a][b],N[a].j--),0==N[a].j&&delete N[a])}}function gc(a,b,c,d,e){var f=1,b=ia(b);if(a[b]){a.q--;a=a[b];a.za?a.za++:a.za=1;try{for(var h=a.length,k=0;k<h;k++){var m=a[k];m&&!m.Z&&(f&=hc(m,e)!==r)}}finally{a.za--,fc(c,d,b,a)}}return Boolean(f)}function hc(a,b){a.mb&&Q(a.key);return a.handleEvent(b)}
function dc(a,b){if(!bc[a])return j;var c=bc[a],d=c.type,e=N;if(!(d in e))return j;var e=e[d],f,h;if(!Wb){var k;if(!(k=b))a:{k=["window","event"];for(var m=y;f=k.shift();)if(m[f]!=l)m=m[f];else{k=l;break a}k=m}f=k;k=j in e;m=r in e;if(k){if(0>f.keyCode||f.returnValue!=i)return j;a:{var n=r;if(0==f.keyCode)try{f.keyCode=-1;break a}catch(s){n=j}if(n||f.returnValue==i)f.returnValue=j}}n=new M;n.na(f,this);f=j;try{if(k){for(var p=[],q=n.currentTarget;q;q=q.parentNode)p.push(q);h=e[j];h.q=h.j;for(var z=
p.length-1;!n.M&&0<=z&&h.q;z--)n.currentTarget=p[z],f&=gc(h,p[z],d,j,n);if(m){h=e[r];h.q=h.j;for(z=0;!n.M&&z<p.length&&h.q;z++)n.currentTarget=p[z],f&=gc(h,p[z],d,r,n)}}else f=hc(c,n)}finally{p&&(p.length=0)}return f}d=new M(b,this);return f=hc(c,d)};function ic(a){this.D=r;this.lc=a;this.e=[]}C(ic,ib);var jc=[];function R(a,b,c,d){"array"!=ea(c)&&(jc[0]=c,c=jc);for(var e=0;e<c.length;e++){var f=P(b,c[e],d||a,r,a.lc||a);a.e.push(f)}return a}ic.prototype.f=function(){ic.a.f.call(this);K(this.e,Q);this.e.length=0};ic.prototype.handleEvent=function(){g(Error("EventHandler.handleEvent not implemented"))};function kc(){}da(kc);kc.prototype.ab=0;kc.la();function lc(){this.D=r}C(lc,ib);x=lc.prototype;x.rb=j;x.Ea=l;x.ib=aa("Ea");x.addEventListener=function(a,b,c,d){P(this,a,b,c,d)};x.removeEventListener=function(a,b,c,d){ec(this,a,b,c,d)};
x.dispatchEvent=function(a){var b=a.type||a,c=N;if(b in c){if(A(a))a=new Yb(a,this);else if(a instanceof Yb)a.target=a.target||this;else{var d=a,a=new Yb(b,this);Va(a,d)}var d=1,e,c=c[b],b=j in c,f;if(b){e=[];for(f=this;f;f=f.Ea)e.push(f);f=c[j];f.q=f.j;for(var h=e.length-1;!a.M&&0<=h&&f.q;h--)a.currentTarget=e[h],d&=gc(f,e[h],a.type,j,a)&&a.Fa!=r}if(r in c)if(f=c[r],f.q=f.j,b)for(h=0;!a.M&&h<e.length&&f.q;h++)a.currentTarget=e[h],d&=gc(f,e[h],a.type,r,a)&&a.Fa!=r;else for(e=this;!a.M&&e&&f.q;e=e.Ea)a.currentTarget=
e,d&=gc(f,e,a.type,r,a)&&a.Fa!=r;a=Boolean(d)}else a=j;return a};x.f=function(){lc.a.f.call(this);var a,b=0,c=a==l;a=!!a;if(this==l)Sa(O,function(d){for(var e=d.length-1;0<=e;e--){var f=d[e];if(c||a==f.capture)Q(f.key),b++}});else{var d=ia(this);if(O[d])for(var d=O[d],e=d.length-1;0<=e;e--){var f=d[e];if(c||a==f.capture)Q(f.key),b++}}this.Ea=l};function S(a){this.D=r;this.va=a||Kb();this.qa=mc}C(S,lc);S.prototype.mc=kc.la();var mc=l;function nc(a,b){switch(a){case 1:return b?"disable":"enable";case 2:return b?"highlight":"unhighlight";case 4:return b?"activate":"deactivate";case 8:return b?"select":"unselect";case 16:return b?"check":"uncheck";case 32:return b?"focus":"blur";case 64:return b?"open":"close"}g(Error("Invalid component state"))}x=S.prototype;x.V=l;x.g=r;x.c=l;x.qa=l;x.$a=l;x.p=l;x.i=l;x.k=l;x.Ec=r;
function T(a){return a.V||(a.V=":"+(a.mc.ab++).toString(36))}x.d=u("c");function oc(a,b){a==b&&g(Error("Unable to set parent component"));b&&(a.p&&a.V&&a.p.k&&a.V&&(a.V in a.p.k&&a.p.k[a.V])&&a.p!=b)&&g(Error("Unable to set parent component"));a.p=b;S.a.ib.call(a,b)}x.getParent=u("p");x.ib=function(a){this.p&&this.p!=a&&g(Error("Method not supported"));S.a.ib.call(this,a)};x.Qa=u("va");x.u=function(){this.c=this.va.createElement("div")};
function pc(a,b,c){a.g&&g(Error("Component already rendered"));a.c||a.u();b?b.insertBefore(a.c,c||l):a.va.F.body.appendChild(a.c);(!a.p||a.p.g)&&a.l()}x.l=function(){this.g=j;qc(this,function(a){!a.g&&a.d()&&a.l()})};x.ja=function(){qc(this,function(a){a.g&&a.ja()});if(this.I){var a=this.I;K(a.e,Q);a.e.length=0}this.g=r};
x.f=function(){S.a.f.call(this);this.g&&this.ja();this.I&&(this.I.B(),delete this.I);qc(this,function(a){a.B()});if(!this.Ec&&this.c){var a=this.c;a&&a.parentNode&&a.parentNode.removeChild(a)}this.p=this.$a=this.c=this.k=this.i=l};x.Ha=aa("$a");
x.R=function(a,b,c){a.g&&(c||!this.g)&&g(Error("Component already rendered"));(0>b||b>(this.i?this.i.length:0))&&g(Error("Child component index out of bounds"));if(!this.k||!this.i)this.k={},this.i=[];if(a.getParent()==this){var d=T(a);this.k[d]=a;$a(this.i,a)}else{var d=this.k,e=T(a);e in d&&g(Error('The object already contains the key "'+e+'"'));d[e]=a}oc(a,this);ab(this.i,b,0,a);a.g&&this.g&&a.getParent()==this?(c=this.ka(),c.insertBefore(a.d(),c.childNodes[b]||l)):c?(this.c||this.u(),b=this.i?
this.i[b+1]||l:l,pc(a,this.ka(),b?b.c:l)):this.g&&(!a.g&&a.c&&a.c.parentNode)&&a.l()};x.ka=u("c");x.ra=function(a){this.g&&g(Error("Component already rendered"));this.qa=a};function qc(a,b){a.i&&K(a.i,b,i)}x.removeChild=function(a,b){if(a){var c=A(a)?a:T(a),a=this.k&&c?(c in this.k?this.k[c]:i)||l:l;if(c&&a){var d=this.k;c in d&&delete d[c];$a(this.i,a);b&&(a.ja(),a.c&&(c=a.c)&&c.parentNode&&c.parentNode.removeChild(c));oc(a,l)}}a||g(Error("Child is not in parent component"));return a};function rc(){}var sc;da(rc);x=rc.prototype;x.u=function(a){var b=a.Qa().u("div",tc(this,a).join(" "),a.Na);a.isEnabled()||uc(b,1,j);a.h&8&&uc(b,8,j);a.t&16&&uc(b,16,!!(a.h&16));a.t&64&&uc(b,64,!!(a.h&64));return b};x.ka=function(a){return a};x.ia=function(a,b,c){if(a=a.d?a.d():a)if(E&&!I("7")){var d=vc(Fb(a),b);d.push(b);oa(c?Gb:Hb,a).apply(l,d)}else c?Gb(a,b):Hb(a,b)};
x.fb=function(a,b){var c=!b,d=E||D?a.getElementsByTagName("*"):l;if(Sb){if(c=c?"none":"",a.style[Sb]=c,d)for(var e=0,f;f=d[e];e++)f.style[Sb]=c}else if(E||D)if(c=c?"on":"",a.setAttribute("unselectable",c),d)for(e=0;f=d[e];e++)f.setAttribute("unselectable",c)};x.ra=function(a,b){this.ia(a,this.T()+"-rtl",b)};function wc(a,b){var c;if(a.t&32&&(c=a.U())){if(!b&&a.h&32){try{c.blur()}catch(d){}a.h&32&&a.zb()}Ob(c)!=b&&(b?c.tabIndex=0:(c.tabIndex=-1,c.removeAttribute("tabIndex")))}}
x.jb=function(a,b){a.style.display=b?"":"none"};x.z=function(a,b,c){var d=a.d();if(d){var e=xc(this,b);e&&this.ia(a,e,c);uc(d,b,c)}};function uc(a,b,c){sc||(sc={1:"disabled",8:"selected",16:"checked",64:"expanded"});(b=sc[b])&&a.setAttribute("aria-"+b,c)}x.U=function(a){return a.d()};x.T=function(){return"goog-control"};
function tc(a,b){var c=a.T(),d=[c],e=a.T();e!=c&&d.push(e);c=b.h;for(e=[];c;){var f=c&-c;e.push(xc(a,f));c&=~f}d.push.apply(d,e);(c=b.w)&&d.push.apply(d,c);E&&!I("7")&&d.push.apply(d,vc(d));return d}function vc(a,b){var c=[];b&&(a=a.concat([b]));K([],function(d){Ya(d,oa(Za,a))&&(!b||Za(d,b))&&c.push(d.join("_"))});return c}function xc(a,b){if(!a.nb){var c=a.T();a.nb={1:c+"-disabled",2:c+"-hover",4:c+"-active",8:c+"-selected",16:c+"-checked",32:c+"-focused",64:c+"-open"}}return a.nb[b]};function yc(a,b){a||g(Error("Invalid class name "+a));B(b)||g(Error("Invalid decorator function "+b))}var zc={};function Ac(a,b,c,d,e){if(!E&&(!H||!I("525")))return j;if(Ha&&e)return Bc(a);if(e&&!d||!c&&(17==b||18==b)||E&&d&&b==a)return r;switch(a){case 13:return!(E&&Ra(9));case 27:return!H}return Bc(a)}function Bc(a){if(48<=a&&57>=a||96<=a&&106>=a||65<=a&&90>=a||H&&0==a)return j;switch(a){case 32:case 63:case 107:case 109:case 110:case 111:case 186:case 59:case 189:case 187:case 61:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return j;default:return r}}
function Cc(a){switch(a){case 61:return 187;case 59:return 186;case 224:return 91;case 0:return 224;default:return a}};function Dc(a,b){this.D=r;a&&Ec(this,a,b)}C(Dc,lc);x=Dc.prototype;x.c=l;x.xa=l;x.Wa=l;x.ya=l;x.K=-1;x.J=-1;
var Fc={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},Gc={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},Hc=E||H&&I("525");x=Dc.prototype;
x.dc=function(a){if(H&&(17==this.K&&!a.ctrlKey||18==this.K&&!a.altKey))this.J=this.K=-1;Hc&&!Ac(a.keyCode,this.K,a.shiftKey,a.ctrlKey,a.altKey)?this.handleEvent(a):this.J=F?Cc(a.keyCode):a.keyCode};x.fc=function(){this.J=this.K=-1};
x.handleEvent=function(a){var b=a.v,c,d;E&&"keypress"==a.type?(c=this.J,d=13!=c&&27!=c?b.keyCode:0):H&&"keypress"==a.type?(c=this.J,d=0<=b.charCode&&63232>b.charCode&&Bc(c)?b.charCode:0):D?(c=this.J,d=Bc(c)?b.keyCode:0):(c=b.keyCode||this.J,d=b.charCode||0,Ha&&(63==d&&224==c)&&(c=191));var e=c,f=b.keyIdentifier;c?63232<=c&&c in Fc?e=Fc[c]:25==c&&a.shiftKey&&(e=9):f&&f in Gc&&(e=Gc[f]);a=e==this.K;this.K=e;b=new Ic(e,d,a,b);this.dispatchEvent(b)};x.d=u("c");
function Ec(a,b,c){a.ya&&a.detach();a.c=b;a.xa=P(a.c,"keypress",a,c);a.Wa=P(a.c,"keydown",a.dc,c,a);a.ya=P(a.c,"keyup",a.fc,c,a)}x.detach=function(){this.xa&&(Q(this.xa),Q(this.Wa),Q(this.ya),this.ya=this.Wa=this.xa=l);this.c=l;this.J=this.K=-1};x.f=function(){Dc.a.f.call(this);this.detach()};function Ic(a,b,c,d){d&&this.na(d,i);this.type="key";this.keyCode=a;this.charCode=b;this.repeat=c}C(Ic,M);function U(a,b,c){S.call(this,c);if(!b){for(var b=this.constructor,d;b;){d=ia(b);if(d=zc[d])break;b=b.a?b.a.constructor:l}b=d?B(d.la)?d.la():new d:l}this.o=b;this.Na=a}C(U,S);x=U.prototype;x.Na=l;x.h=0;x.t=39;x.Vb=255;x.xc=0;x.ca=j;x.w=l;x.hc=j;x.La=r;x.tc=l;x.U=function(){return this.o.U(this)};x.ia=function(a,b){b?a&&(this.w?Za(this.w,a)||this.w.push(a):this.w=[a],this.o.ia(this,a,j)):a&&this.w&&($a(this.w,a),0==this.w.length&&(this.w=l),this.o.ia(this,a,r))};
x.u=function(){var a=this.o.u(this);this.c=a;var b=this.tc||i;b&&a.setAttribute("role",b);this.La||this.o.fb(a,r);this.ca||this.o.jb(a,r)};x.ka=function(){return this.o.ka(this.d())};
x.l=function(){U.a.l.call(this);var a=this.o;this.qa==l&&(this.qa="rtl"==Pb(this.g?this.c:this.va.F.body,"direction"));this.qa&&a.ra(this.d(),j);this.isEnabled()&&wc(this,this.ca);if(this.t&-2){if(this.hc){var a=this.I||(this.I=new ic(this)),b=this.d();R(R(R(R(a,b,"mouseover",this.jc),b,"mousedown",this.gc),b,"mouseup",this.kc),b,"mouseout",this.ic);this.Ab!=ca&&R(a,b,"contextmenu",this.Ab);E&&R(a,b,"dblclick",this.bc)}if(this.t&32&&(a=this.U()))b=this.W||(this.W=new Dc),Ec(b,a),R(R(R(this.I||(this.I=
new ic(this)),b,"key",this.ec),a,"focus",this.cc),a,"blur",this.zb)}};x.ja=function(){U.a.ja.call(this);this.W&&this.W.detach();this.ca&&this.isEnabled()&&wc(this,r)};x.f=function(){U.a.f.call(this);this.W&&(this.W.B(),delete this.W);delete this.o;this.w=this.Na=l};x.ra=function(a){U.a.ra.call(this,a);var b=this.d();b&&this.o.ra(b,a)};x.fb=function(a){this.La=a;var b=this.d();b&&this.o.fb(b,a)};
x.jb=function(a,b){if(b||this.ca!=a&&this.dispatchEvent(a?"show":"hide")){var c=this.d();c&&this.o.jb(c,a);this.isEnabled()&&wc(this,a);this.ca=a;return j}return r};x.isEnabled=function(){return!(this.h&1)};function Jc(a,b){Kc(a,2,b)&&a.z(2,b)}x.setActive=function(a){Kc(this,4,a)&&this.z(4,a)};x.z=function(a,b){this.t&a&&b!=!!(this.h&a)&&(this.o.z(this,a,b),this.h=b?this.h|a:this.h&~a)};function Lc(a,b){a.g&&a.h&b&&g(Error("Component already rendered"));a.h&b&&a.z(b,r);a.t&=~b}
function V(a,b){return!!(a.Vb&b)&&!!(a.t&b)}function Kc(a,b,c){return!!(a.t&b)&&!!(a.h&b)!=c&&(!(a.xc&b)||a.dispatchEvent(nc(b,c)))&&!a.D}x.jc=function(a){!Mc(a,this.d())&&(this.dispatchEvent("enter")&&this.isEnabled()&&V(this,2))&&Jc(this,j)};x.ic=function(a){!Mc(a,this.d())&&this.dispatchEvent("leave")&&(V(this,4)&&this.setActive(r),V(this,2)&&Jc(this,r))};x.Ab=ca;function Mc(a,b){return!!a.relatedTarget&&yb(b,a.relatedTarget)}
x.gc=function(a){if(this.isEnabled()&&(V(this,2)&&Jc(this,j),ac(a)&&(!H||!Ha||!a.ctrlKey))){V(this,4)&&this.setActive(j);var b;this.t&32&&(b=this.U())&&Ob(b)&&this.U().focus()}!this.La&&(ac(a)&&(!H||!Ha||!a.ctrlKey))&&a.preventDefault()};x.kc=function(a){this.isEnabled()&&(V(this,2)&&Jc(this,j),this.h&4&&(Nc(this,a)&&V(this,4))&&this.setActive(r))};x.bc=function(a){this.isEnabled()&&Nc(this,a)};
function Nc(a,b){if(V(a,16)){var c=!(a.h&16);Kc(a,16,c)&&a.z(16,c)}V(a,8)&&Kc(a,8,j)&&a.z(8,j);V(a,64)&&(c=!(a.h&64),Kc(a,64,c)&&a.z(64,c));c=new Yb("action",a);b&&(c.altKey=b.altKey,c.ctrlKey=b.ctrlKey,c.metaKey=b.metaKey,c.shiftKey=b.shiftKey,c.eb=b.eb);return a.dispatchEvent(c)}x.cc=function(){V(this,32)&&Kc(this,32,j)&&this.z(32,j)};x.zb=function(){V(this,4)&&this.setActive(r);V(this,32)&&Kc(this,32,r)&&this.z(32,r)};
x.ec=function(a){return this.ca&&this.isEnabled()&&13==a.keyCode&&Nc(this,a)?(a.preventDefault(),a.stopPropagation(),j):r};B(U)||g(Error("Invalid component class "+U));B(rc)||g(Error("Invalid renderer class "+rc));var Oc=ia(U);zc[Oc]=rc;yc("goog-control",function(){return new U(l)});function Pc(){}C(Pc,rc);da(Pc);Pc.prototype.u=function(a){return a.Qa().u("div",this.T())};Pc.prototype.T=function(){return"goog-menuseparator"};function Qc(a,b){U.call(this,l,a||Pc.la(),b);Lc(this,1);Lc(this,2);Lc(this,4);Lc(this,32);this.h=1}C(Qc,U);Qc.prototype.l=function(){Qc.a.l.call(this);this.d().setAttribute("role","separator")};yc("goog-menuseparator",function(){return new Qc});function W(){S.call(this);vb||(vb=j,P(window,"load",function(){P(document.body,wb,xb)}));ub[T(this)]=this}C(W,S);x=W.prototype;x.ea=t();x.u=function(){this.c=Bb(this.O())};x.Ha=function(a){W.a.Ha.call(this,a);this.b=this.$a};x.R=function(a,b,c){c!=r&&(c=j);W.a.R.call(this,a,b,c)};x.Ub=function(a,b){var c=this;a.forEach(function(a){c.R(a,c.i?c.i.length:0,b)},this)};x.wa=function(){var a=this,b=[];qc(this,function(a){b.push(T(a))});return b.map(function(b){return a.k&&b?(b in a.k?a.k[b]:i)||l:l})};
x.f=function(){W.a.f.call(this);this.b=l};x.P=function(a){return Ab(a,this.d())};x.O=function(){return'<div id="'+T(this)+'"></div>'};function Rc(){}C(Rc,lc);function X(a,b,c){a instanceof Function?this.Wb=a:this.param=a;this.name=b;this.Aa=c;this.value=0}C(X,Rc);X.prototype.aa=function(a){var b=this.value,a=Math.min(a,10),a=Math.max(a,0);this.Kb(a,b);a={type:Sc,newValue:this.value,oldValue:b};this.param?this.param.value=this.value:this.Wb(this.value,b);this.dispatchEvent(a)};X.prototype.Kb=function(a){this.value=a*this.Aa};X.prototype.Ra=function(){return this.value/this.Aa};var Sc="valueChanged";function Y(a,b,c){this.Ha(new this.m(a,b,c||1));this.ea();this.aa(10);W.call(this)}C(Y,W);x=Y.prototype;x.m=X;x.lb=26;x.aa=function(a){this.b.aa(a)};x.ba=function(){if(this.g){var a="rotateZ("+this.b.Ra()*this.lb+"deg)";this.P(this.r.kb)[0].style["-webkit-transform"]=a}};x.O=function(){return'<div class="pot" id="'+T(this)+'"><div class="knobHolder"><img class="knob" src="img/pot-small.png"/></div><div class="nameHolder"><div class="name">'+this.b.name+"</div></div></div>"};
x.l=function(){Y.a.l.call(this);this.ba()};x.r={kb:".knob",Qb:".knobHolder"};x.ea=function(){P(this.b,Sc,this.ba,r,this)};var Tc=Y.prototype;Tc.H={};(Tc.H.mousedown={})[Tc.r.kb]=function(a){this.xb=j;this.Hb=a.clientY;var b=P(document.body,"mouseup",function(){this.xb=r;Q(c);Q(b)},r,this),c=P(document.body,"mousemove",function(a){this.xb&&(this.aa(this.b.Ra()-(a.clientY-this.Hb)*this.lb/360),this.Hb=a.clientY)},r,this)};function Uc(a,b,c){X.call(this,a,b,c)}C(Uc,X);function Vc(a,b,c){Y.call(this,a,b,c)}C(Vc,Y);Vc.prototype.m=Uc;var Wc={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",
darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",
ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",grey:"#808080",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};function Xc(a){var b={},a=String(a),c="#"==a.charAt(0)?a:"#"+a;if(Yc.test(c))return b.Ua=Zc(c),b.type="hex",b;a:{var d=a.match($c);if(d){var c=Number(d[1]),e=Number(d[2]),d=Number(d[3]);if(0<=c&&255>=c&&0<=e&&255>=e&&0<=d&&255>=d){c=[c,e,d];break a}}c=[]}if(c.length)return e=c[0],a=c[1],c=c[2],e=Number(e),a=Number(a),c=Number(c),(isNaN(e)||0>e||255<e||isNaN(a)||0>a||255<a||isNaN(c)||0>c||255<c)&&g(Error('"('+e+","+a+","+c+'") is not a valid RGB color')),e=ad(e.toString(16)),a=ad(a.toString(16)),c=
ad(c.toString(16)),b.Ua="#"+e+a+c,b.type="rgb",b;if(Wc&&(c=Wc[a.toLowerCase()]))return b.Ua=c,b.type="named",b;g(Error(a+" is not a valid color string"))}var bd=/#(.)(.)(.)/;function Zc(a){Yc.test(a)||g(Error("'"+a+"' is not a valid hex color"));4==a.length&&(a=a.replace(bd,"#$1$1$2$2$3$3"));return a.toLowerCase()}var Yc=/^#(?:[0-9a-f]{3}){1,2}$/i,$c=/^(?:rgb)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\)$/i;function ad(a){return 1==a.length?"0"+a:a};function cd(a,b,c){function d(a,b,c,d,e){return a+"px "+b+"px "+c+"px "+((e||0)+"px")+" hsl("+m[0]+", "+100*m[1]+"%, "+d+"%)"}var e,f,h=0.5;e=e||[];f=f||[];var k=document.defaultView.getComputedStyle(a,l).getPropertyValue("background-color"),m,n,k=Xc(k).Ua,k=Zc(k);n=[parseInt(k.substr(1,2),16),parseInt(k.substr(3,2),16),parseInt(k.substr(5,2),16)];var k=n[0]/255,s=n[1]/255;n=n[2]/255;var p=Math.max(k,s,n),q=Math.min(k,s,n),z=0,v=0,fa=0.5*(p+q);p!=q&&(p==k?z=60*(s-n)/(p-q):p==s?z=60*(n-k)/(p-q)+120:
p==n&&(z=60*(k-s)/(p-q)+240),v=0<fa&&0.5>=fa?(p-q)/(2*fa):(p-q)/(2-2*fa));m=[Math.round(z+360)%360,v,fa];m[2]*=h||1;h=[];k=(window.innerWidth/2-Rb(a).x-a.offsetWidth/2)/30;s=(window.innerHeight-Rb(a).y-a.offsetHeight/2)/80*b/10;for(n=b;b--;)h.push(d(k*b/n,2*s*b/n,0,100*m[2]-100*m[2]*(b+5)/n/1.6));h.splice(0,0,d(k,2*s,4*n,0,0),d(k/c/8,3*s,4*n,30,n/12),d(k/c/8,2*s,n,0,n/4/c),d(k/c/8,2.55*s,2*n,5,n/3/c));h=[].concat(e,h.reverse(),f);a.style.boxShadow=h.join(", ");a.style.left="-"+k/2+"px"};function dd(a){this.name=a;this.oa=[[],[],[]];this.state=r}C(dd,Rc);dd.prototype.toggle=function(){var a=this.state;if(this.state=!this.state){var b=function(a){a[1].disconnect();a[0]&&a[1].connect(a[0])};K(this.oa,function(a){a&&(b(a),setTimeout(function(){b(a)},10))})}else{var c=function(a){a[1].disconnect();a[2]&&a[1].connect(a[2])};K(this.oa,function(a){c(a);setTimeout(function(){c(a)},10)})}this.dispatchEvent({type:this.state?ed:fd,newValue:this.state,oldValue:a})};
dd.prototype.hb=function(a){this.oa=a;this.state=!this.state;this.toggle()};var ed="on",fd="off";function gd(a){this.b=new this.m(a);W.call(this)}C(gd,W);x=gd.prototype;x.m=dd;x.hb=function(a){this.b.hb(a)};x.bb=function(){this.b.toggle()};x.O=function(){return'<div class="switch" id="'+T(this)+'"><img class="button" src="img/switch.png"/>'+(this.b.name?'<div class="name">'+this.b.name+"</div>":"")+"</div>"};x.r={Ja:".button"};var hd=gd.prototype;hd.H={};(hd.H.click={})[hd.r.Ja]=hd.bb;function id(a){dd.call(this,a);this.state=r}C(id,dd);function jd(a){gd.call(this,a);this.state=r}C(jd,gd);jd.prototype.m=id;var kd=jd.prototype;kd.H={};var ld=kd.H.mousedown={},md=kd.H.mouseup={};ld[kd.r.Ja]=kd.bb;md[kd.r.Ja]=kd.bb;function Z(a){W.call(this);this.Ha(new this.m(a));this.pb();this.ea()}C(Z,W);x=Z.prototype;x.m=sb;x.pb=function(){this.Fc=[]};x.C=function(){return this.b.C()};x.ma=function(){return this.b.ma()};x.$=function(a){this.b.$(a.ma())};x.connect=function(a){a.$(this);this.b.connect(a.C())};x.disconnect=function(){this.b.disconnect()};function nd(a,b){W.call(this);this.yb=a;this.name=b||"";this.state=r;this.ea()}C(nd,W);x=nd.prototype;x.toggle=function(){this.state=!this.state;this.ba()};x.ba=function(){if(this.g){var a=this.d();this.state?Gb(a,"on"):Hb(a,"on")}};x.O=function(){return'<div class="led" id="'+T(this)+'"><div class="nameHolder"><div class="name">'+this.name+"</div></div></div>"};x.l=function(){nd.a.l.call(this);this.ba()};x.ea=function(){this.yb&&P(this.yb.b,[ed,fd],this.rc,r,this)};
x.rc=function(a){this.state=a.newValue;this.ba()};function od(a){dd.call(this,a);this.state=j}C(od,dd);function pd(a){gd.call(this,a)}C(pd,gd);pd.prototype.m=od;function qd(a){Z.call(this,a)}C(qd,Z);x=qd.prototype;x.m=L;x.pb=function(){this.ha();this.ta=new pd;this.nc=new nd(this.ta);this.oc=[this.nc];this.yc=[this.ta];var a=this;P(this.ta.b,ed,function(){this.b.s();setTimeout(function(){a.b.s()},10)},r,this)};x.ha=function(){this.da=new Vc(this.b.X.gain,"volume",0.1);this.pa=[this.da]};x.connect=function(a){qd.a.connect.call(this,a);this.ta.hb(this.b.oa)};x.Ga=function(a){this.da.aa(a)};
x.O=function(){return'<div id="'+T(this)+'" class="box '+this.name+'"><div class="pots"></div><div class="name">'+this.name+'</div><div class="leds"></div><div class="switches"></div></div>'};x.l=function(){qd.a.l.call(this);this.pa.forEach(function(a){var b=this.P(this.r.Sb)[0];pc(a,b)},this);this.yc.forEach(function(a){var b=this.P(this.r.Tb)[0];pc(a,b)},this);this.oc.forEach(function(a){var b=this.P(this.r.Rb)[0];pc(a,b)},this)};x.r={Sb:".pots",Tb:".switches",Rb:".leds"};x.name="pb";function rd(a){Z.call(this,a)}C(rd,qd);rd.prototype.m=tb;rd.prototype.name="convo";rd.prototype.ha=function(){this.da=new Y(this.b.ob.gain,"effect",1);this.pa=[].concat(this.da)};function sd(a){L.call(this,a)}C(sd,L);function td(a){Z.call(this,a)}C(td,qd);td.prototype.m=sd;td.prototype.name="volume";function ud(a){L.call(this,a);this.pc=3E3;this.Ya=this.context.createBiquadFilter();this.Ya.type=0;this.Ya.frequency.value=this.pc;this.Ob=this.context.createWaveShaper();this.G=[this.Ob,this.Ya,this.X]}C(ud,L);ud.prototype.gb=function(a){this.Pb=new Float32Array(22050);for(var b=Math.PI/180,c=0;22050>c;c+=1){var d=2*c/22050-1;this.Pb[c]=20*((3+a)*d)*b/(Math.PI+a*Math.abs(d))}this.Ob.curve=this.Pb};function vd(a,b,c){X.call(this,a,b,c)}C(vd,X);vd.prototype.Kb=function(a){a=Math.pow(a,3)/100;this.value=a*this.Aa};vd.prototype.Ra=function(){return Math.round(100*Math.pow(100*this.value/this.Aa,1/3))/100};function wd(a,b,c){Y.call(this,a,b,c)}C(wd,Y);wd.prototype.m=vd;function xd(a){Z.call(this,a)}C(xd,qd);xd.prototype.m=ud;xd.prototype.ha=function(){xd.a.ha.call(this);var a=na(this.b.gb,this.b);this.ub=new wd(a,"drive",200);this.pa.push(this.ub)};xd.prototype.gb=function(a){this.ub.aa(a)};xd.prototype.name="overdrive";var yd;yd=function(){return j};/*
 Portions of this code are from the Dojo Toolkit, received by
 The Closure Library Authors under the BSD license. All other code is
 Copyright 2005-2009 The Closure Library Authors. All Rights Reserved.

The "New" BSD License:

Copyright (c) 2005-2009, The Dojo Foundation
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.
 Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.
 Neither the name of the Dojo Foundation nor the names of its contributors
    may be used to endorse or promote products derived from this software
    without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
var Ab;function zd(a,b){var c=b||[];a&&c.push(a);return c}var Ad=H&&"BackCompat"==document.compatMode,Bd=document.firstChild.children?"children":"childNodes",Cd=r;
function Dd(a){function b(){0<=n&&(w.id=c(n,v).replace(/\\/g,""),n=-1);if(0<=s){var a=s==v?l:c(s,v);0>">~+".indexOf(a)?w.n=a:w.Ca=a;s=-1}0<=m&&(w.A.push(c(m+1,v).replace(/\\/g,"")),m=-1)}function c(b,c){return qa(a.slice(b,c))}for(var a=0<=">~+".indexOf(a.slice(-1))?a+" * ":a+" ",d=[],e=-1,f=-1,h=-1,k=-1,m=-1,n=-1,s=-1,p="",q="",z,v=0,fa=a.length,w=l,G=l;p=q,q=a.charAt(v),v<fa;v++)if("\\"!=p)if(w||(z=v,w={Y:l,N:[],sa:[],A:[],n:l,Ca:l,id:l,Sa:function(){return Cd?this.sc:this.n}},s=v),0<=e)if("]"==
q){G.attr?G.Za=c(h||e+1,v):G.attr=c(e+1,v);if((e=G.Za)&&('"'==e.charAt(0)||"'"==e.charAt(0)))G.Za=e.slice(1,-1);w.sa.push(G);G=l;e=h=-1}else"="==q&&(h=0<="|~^$*".indexOf(p)?p:"",G.type=h+q,G.attr=c(e+1,v-h.length),h=v+1);else 0<=f?")"==q&&(0<=k&&(G.value=c(f+1,v)),k=f=-1):"#"==q?(b(),n=v+1):"."==q?(b(),m=v):":"==q?(b(),k=v):"["==q?(b(),e=v,G={}):"("==q?(0<=k&&(G={name:c(k+1,v),value:l},w.N.push(G)),f=v):" "==q&&p!=q&&(b(),0<=k&&w.N.push({name:c(k+1,v)}),w.Fb=w.N.length||w.sa.length||w.A.length,w.Hc=
w.Y=c(z,v),w.sc=w.n=w.Ca?l:w.n||"*",w.n&&(w.n=w.n.toUpperCase()),d.length&&d[d.length-1].Ca&&(w.Cb=d.pop(),w.Y=w.Cb.Y+" "+w.Y),d.push(w),w=l);return d}function Ed(a,b){return!a?b:!b?a:function(){return a.apply(window,arguments)&&b.apply(window,arguments)}}function Fd(a){return 1==a.nodeType}function Gd(a,b){return!a?"":"class"==b?a.className||"":"for"==b?a.htmlFor||"":"style"==b?a.style.cssText||"":(Cd?a.getAttribute(b):a.getAttribute(b,2))||""}
var Hd={"*=":function(a,b){return function(c){return 0<=Gd(c,a).indexOf(b)}},"^=":function(a,b){return function(c){return 0==Gd(c,a).indexOf(b)}},"$=":function(a,b){return function(c){c=" "+Gd(c,a);return c.lastIndexOf(b)==c.length-b.length}},"~=":function(a,b){var c=" "+b+" ";return function(b){return 0<=(" "+Gd(b,a)+" ").indexOf(c)}},"|=":function(a,b){b=" "+b;return function(c){c=" "+Gd(c,a);return c==b||0==c.indexOf(b+"-")}},"=":function(a,b){return function(c){return Gd(c,a)==b}}},Id="undefined"==
typeof document.firstChild.nextElementSibling,Jd=!Id?"nextElementSibling":"nextSibling",Kd=!Id?"previousElementSibling":"previousSibling",Ld=Id?Fd:yd;function Md(a){for(;a=a[Kd];)if(Ld(a))return r;return j}function Nd(a){for(;a=a[Jd];)if(Ld(a))return r;return j}function Od(a){var b=a.parentNode,c=0,d=b[Bd],e=a._i||-1,f=b._l||-1;if(!d)return-1;d=d.length;if(f==d&&0<=e&&0<=f)return e;b._l=d;e=-1;for(b=b.firstElementChild||b.firstChild;b;b=b[Jd])Ld(b)&&(b._i=++c,a===b&&(e=c));return e}
function Pd(a){return!(Od(a)%2)}function Qd(a){return Od(a)%2}
var Sd={checked:function(){return function(a){return a.checked||a.attributes.checked}},"first-child":function(){return Md},"last-child":function(){return Nd},"only-child":function(){return function(a){return!Md(a)||!Nd(a)?r:j}},empty:function(){return function(a){for(var b=a.childNodes,a=a.childNodes.length-1;0<=a;a--){var c=b[a].nodeType;if(1===c||3==c)return r}return j}},contains:function(a,b){var c=b.charAt(0);if('"'==c||"'"==c)b=b.slice(1,-1);return function(a){return 0<=a.innerHTML.indexOf(b)}},
not:function(a,b){var c=Dd(b)[0],d={S:1};"*"!=c.n&&(d.n=1);c.A.length||(d.A=1);var e=Rd(c,d);return function(a){return!e(a)}},"nth-child":function(a,b){if("odd"==b)return Qd;if("even"==b)return Pd;if(-1!=b.indexOf("n")){var c=b.split("n",2),d=c[0]?"-"==c[0]?-1:parseInt(c[0],10):1,e=c[1]?parseInt(c[1],10):0,f=0,h=-1;0<d?0>e?e=e%d&&d+e%d:0<e&&(e>=d&&(f=e-e%d),e%=d):0>d&&(d*=-1,0<e&&(h=e,e%=d));if(0<d)return function(a){a=Od(a);return a>=f&&(0>h||a<=h)&&a%d==e};b=e}var k=parseInt(b,10);return function(a){return Od(a)==
k}}},Td=E?function(a){var b=a.toLowerCase();"class"==b&&(a="className");return function(c){return Cd?c.getAttribute(a):c[a]||c[b]}}:function(a){return function(b){return b&&b.getAttribute&&b.hasAttribute(a)}};
function Rd(a,b){if(!a)return yd;var b=b||{},c=l;b.S||(c=Ed(c,Fd));b.n||"*"!=a.n&&(c=Ed(c,function(b){return b&&b.tagName==a.Sa()}));b.A||K(a.A,function(a,b){var f=RegExp("(?:^|\\s)"+a+"(?:\\s|$)");c=Ed(c,function(a){return f.test(a.className)});c.count=b});b.N||K(a.N,function(a){var b=a.name;Sd[b]&&(c=Ed(c,Sd[b](b,a.value)))});b.sa||K(a.sa,function(a){var b,f=a.attr;a.type&&Hd[a.type]?b=Hd[a.type](f,a.Za):f.length&&(b=Td(f));b&&(c=Ed(c,b))});b.id||a.id&&(c=Ed(c,function(b){return!!b&&b.id==a.id}));
c||"default"in b||(c=yd);return c}var Ud={};
function Vd(a){var b=Ud[a.Y];if(b)return b;var c=a.Cb,c=c?c.Ca:"",d=Rd(a,{S:1}),e="*"==a.n,f=document.getElementsByClassName;if(c)if(f={S:1},e&&(f.n=1),d=Rd(a,f),"+"==c)var h=d,b=function(a,b,c){for(;a=a[Jd];)if(!Id||Fd(a)){(!c||Wd(a,c))&&h(a)&&b.push(a);break}return b};else if("~"==c)var k=d,b=function(a,b,c){for(a=a[Jd];a;){if(Ld(a)){if(c&&!Wd(a,c))break;k(a)&&b.push(a)}a=a[Jd]}return b};else{if(">"==c)var m=d,m=m||yd,b=function(a,b,c){for(var d=0,e=a[Bd];a=e[d++];)Ld(a)&&((!c||Wd(a,c))&&m(a,d))&&
b.push(a);return b}}else if(a.id)d=!a.Fb&&e?yd:Rd(a,{S:1,id:1}),b=function(b,c){var e=Kb(b).d(a.id),f;if(f=e&&d(e))if(!(f=9==b.nodeType)){for(f=e.parentNode;f&&f!=b;)f=f.parentNode;f=!!f}if(f)return zd(e,c)};else if(f&&/\{\s*\[native code\]\s*\}/.test(String(f))&&a.A.length&&!Ad)var d=Rd(a,{S:1,A:1,id:1}),n=a.A.join(" "),b=function(a,b){for(var c=zd(0,b),e,f=0,h=a.getElementsByClassName(n);e=h[f++];)d(e,a)&&c.push(e);return c};else!e&&!a.Fb?b=function(b,c){for(var d=zd(0,c),e,f=0,h=b.getElementsByTagName(a.Sa());e=
h[f++];)d.push(e);return d}:(d=Rd(a,{S:1,n:1,id:1}),b=function(b,c){for(var e=zd(0,c),f,h=0,k=b.getElementsByTagName(a.Sa());f=k[h++];)d(f,b)&&e.push(f);return e});return Ud[a.Y]=b}var Xd={},Yd={};function Zd(a){var b=Dd(qa(a));if(1==b.length){var c=Vd(b[0]);return function(a){if(a=c(a,[]))a.Ba=j;return a}}return function(a){for(var a=zd(a),c,f,h=b.length,k,m,n=0;n<h;n++){m=[];c=b[n];f=a.length-1;0<f&&(k={},m.Ba=j);f=Vd(c);for(var s=0;c=a[s];s++)f(c,m,k);if(!m.length)break;a=m}return m}}
var $d=!!document.querySelectorAll&&(!H||I("526"));
function ae(a,b){if($d){var c=Yd[a];if(c&&!b)return c}if(c=Xd[a])return c;var c=a.charAt(0),d=-1==a.indexOf(" ");0<=a.indexOf("#")&&d&&(b=j);if($d&&!b&&-1==">~+".indexOf(c)&&(!E||-1==a.indexOf(":"))&&!(Ad&&0<=a.indexOf("."))&&-1==a.indexOf(":contains")&&-1==a.indexOf("|=")){var e=0<=">~+".indexOf(a.charAt(a.length-1))?a+" *":a;return Yd[a]=function(b){try{9==b.nodeType||d||g("");var c=b.querySelectorAll(e);E?c.Zb=j:c.Ba=j;return c}catch(f){return ae(a,j)(b)}}}var f=a.split(/\s*,\s*/);return Xd[a]=
2>f.length?Zd(a):function(a){for(var b=0,c=[],d;d=f[b++];)c=c.concat(Zd(d)(a));return c}}var be=0,ce=E?function(a){return Cd?a.getAttribute("_uid")||a.setAttribute("_uid",++be)||be:a.uniqueID}:function(a){return a._uid||(a._uid=++be)};function Wd(a,b){if(!b)return 1;var c=ce(a);return!b[c]?b[c]=1:0}
function de(a){if(a&&a.Ba)return a;var b=[];if(!a||!a.length)return b;a[0]&&b.push(a[0]);if(2>a.length)return b;be++;if(E&&Cd){var c=be+"";a[0].setAttribute("_zipIdx",c);for(var d=1,e;e=a[d];d++)a[d].getAttribute("_zipIdx")!=c&&b.push(e),e.setAttribute("_zipIdx",c)}else if(E&&a.Zb)try{for(d=1;e=a[d];d++)Fd(e)&&b.push(e)}catch(f){}else{a[0]&&(a[0]._zipIdx=be);for(d=1;e=a[d];d++)a[d]._zipIdx!=be&&b.push(e),e._zipIdx=be}return b}
function ee(a,b){if(!a)return[];if(a.constructor==Array)return a;if(!A(a))return[a];if(A(b)&&(b=A(b)?document.getElementById(b):b,!b))return[];var b=b||document,c=b.ownerDocument||b.documentElement;Cd=b.contentType&&"application/xml"==b.contentType||D&&(b.doctype||"[object XMLDocument]"==c.toString())||!!c&&(E?c.xml:b.xmlVersion||c.xmlVersion);return(c=ae(a)(b))&&c.Ba?c:de(c)}ee.N=Sd;Ab=ee;ba("goog.dom.query",Ab);ba("goog.dom.query.pseudos",Ab.N);function fe(a){L.call(this,a);this.ga=this.context.createConvolver();this.G=[this.ga,this.X];this.Xa()}C(fe,L);fe.prototype.Va="audio/ir/reverb/pcm90cleanplate.wav";fe.prototype.s=function(){fe.a.s.call(this);this.inputBuffer.connect(this.outputBuffer)};fe.prototype.Xa=function(){var a=this,b=new XMLHttpRequest;b.open("GET",this.Va,j);b.responseType="arraybuffer";b.onload=function(){a.context.decodeAudioData(b.response,function(b){a.ga.buffer=b})};b.send()};function ge(a){Z.call(this,a)}C(ge,qd);ge.prototype.m=fe;ge.prototype.name="reverb";ge.prototype.ha=function(){this.da=new Y(this.b.X.gain,"effect",0.1);this.pa=[].concat(this.da)};function he(a){Z.call(this,a);this.context=a}C(he,Z);function ie(a){a.wa().forEach(function(a){cd(a.d(),40,0.7);a.pa.forEach(function(a){cd(a.P(a.r.Qb)[0],10,4)})})}x=he.prototype;x.R=function(a,b,c){he.a.R.call(this,a,b,c);this.s();this.g&&ie(this)};x.l=function(){he.a.l.call(this);ie(this)};x.O=function(){return'<div id="'+T(this)+'" class="board"></div>'};x.connect=function(a){he.a.connect.call(this,a);this.Da=a;this.s()};
x.s=function(){var a=this.wa();a.length&&(a.forEach(function(b,c){b.disconnect();a[c+1]&&b.connect(a[c+1])}),this.C().disconnect(),this.C().connect(a[0].C()),a.length&&this.Da&&a[a.length-1].connect(this.Da))};x.f=function(){this.wa().forEach(function(a){a.f()});he.a.f.call(this)};function je(a){this.source=a.destination}x=je.prototype;x.C=u("source");x.$=aa("prev");x.connect=t();x.ma=t();x.disconnect=t();function ke(a){this.source=a.createBufferSource();this.source.loop=j}C(ke,lc);x=ke.prototype;x.play=function(a){this.source.noteOn(a||0)};x.connect=function(a){a.$(this);this.source.connect(a.C())};x.disconnect=function(){this.source.disconnect()};x.ma=u("source");x.$=t();x.C=t();function le(a,b){ke.call(this,a);var c=this,d=new XMLHttpRequest;d.open("GET",b,j);d.responseType="arraybuffer";d.onload=function(){a.decodeAudioData(d.response,function(a){c.source.buffer=a;c.dispatchEvent("loaded")})};d.send()}C(le,ke);function me(){W.call(this);this.context=new webkitAudioContext;this.input=new le(this.context,"audio/samples/sample.mp3");this.Da=new je(this.context)}C(me,W);me.prototype.getContext=u("context");me.prototype.play=function(){this.input.play()};me.prototype.O=function(){return'<div id="'+T(this)+'" class="stage"></div>'};ba("pb",function(){this.Ia=new me;pc(this.Ia,i);var a=this.Ia.getContext(),b=new he(a),c=this.Ia;c.fa&&c.fa.B();c.fa=b;c.input.disconnect();c.input.connect(c.fa);c.fa.connect(c.Da);c.R(c.fa,c.i?c.i.length:0,i);this.cb=new xd(a);this.Lb=new ge(a);this.volume=new td(a);this.uc=new rd(a);W.prototype.Ub.call(b,[this.cb,this.Lb,this.volume,this.uc]);this.cb.gb(4);this.cb.Ga(6);this.volume.Ga(10);this.uc.Ga(3);this.Lb.Ga(3);this.Ia.play()});})()
