(function(){function g(a){throw a;}var i=void 0,j=!0,l=null,s=!1;function t(){return function(){}}function aa(a){return function(b){this[a]=b}}function u(a){return function(){return this[a]}}var x,y=this;function ba(a,b){var c=a.split("."),d=y;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var f;c.length&&(f=c.shift());)!c.length&&b!==i?d[f]=b:d=d[f]?d[f]:d[f]={}}function ca(){}function da(a){a.sa=function(){return a.Fb?a.Fb:a.Fb=new a}}
function ea(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function ga(a){var b=ea(a);return"array"==b||"object"==b&&"number"==typeof a.length}function A(a){return"string"==typeof a}function B(a){return"function"==ea(a)}function ha(a){var b=typeof a;return"object"==b&&a!=l||"function"==b}function ia(a){return a[ja]||(a[ja]=++ka)}var ja="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),ka=0;function la(a,b,c){return a.call.apply(a.bind,arguments)}
function ma(a,b,c){a||g(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function na(a,b,c){na=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?la:ma;return na.apply(l,arguments)}
function oa(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}}var pa=Date.now||function(){return+new Date};function C(a,b){function c(){}c.prototype=b.prototype;a.a=b.prototype;a.prototype=new c;a.prototype.constructor=a};function qa(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}function ra(a){if(!sa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ta,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(ua,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(va,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(wa,"&quot;"));return a}var ta=/&/g,ua=/</g,va=/>/g,wa=/\"/g,sa=/[&<>\"]/;var xa,ya,za,Aa,Ba;function Ca(){return y.navigator?y.navigator.userAgent:l}Ba=Aa=za=ya=xa=s;var Da;if(Da=Ca()){var Ea=y.navigator;xa=0==Da.indexOf("Opera");ya=!xa&&-1!=Da.indexOf("MSIE");Aa=(za=!xa&&-1!=Da.indexOf("WebKit"))&&-1!=Da.indexOf("Mobile");Ba=!xa&&!za&&"Gecko"==Ea.product}var D=xa,E=ya,F=Ba,H=za,Fa=Aa,Ga=y.navigator,Ha=-1!=(Ga&&Ga.platform||"").indexOf("Mac"),Ia;
a:{var Ja="",Ka;if(D&&y.opera)var La=y.opera.version,Ja="function"==typeof La?La():La;else if(F?Ka=/rv\:([^\);]+)(\)|;)/:E?Ka=/MSIE\s+([^\);]+)(\)|;)/:H&&(Ka=/WebKit\/(\S+)/),Ka)var Ma=Ka.exec(Ca()),Ja=Ma?Ma[1]:"";if(E){var Na,Oa=y.document;Na=Oa?Oa.documentMode:i;if(Na>parseFloat(Ja)){Ia=String(Na);break a}}Ia=Ja}var Pa={};
function I(a){var b;if(!(b=Pa[a])){b=0;for(var c=qa(String(Ia)).split("."),d=qa(String(a)).split("."),f=Math.max(c.length,d.length),e=0;0==b&&e<f;e++){var h=c[e]||"",k=d[e]||"",m=RegExp("(\\d*)(\\D*)","g"),n=RegExp("(\\d*)(\\D*)","g");do{var p=m.exec(h)||["","",""],q=n.exec(k)||["","",""];if(0==p[0].length&&0==q[0].length)break;b=((0==p[1].length?0:parseInt(p[1],10))<(0==q[1].length?0:parseInt(q[1],10))?-1:(0==p[1].length?0:parseInt(p[1],10))>(0==q[1].length?0:parseInt(q[1],10))?1:0)||((0==p[2].length)<
(0==q[2].length)?-1:(0==p[2].length)>(0==q[2].length)?1:0)||(p[2]<q[2]?-1:p[2]>q[2]?1:0)}while(0==b)}b=Pa[a]=0<=b}return b}var Qa={};function Ra(a){return Qa[a]||(Qa[a]=E&&!!document.documentMode&&document.documentMode>=a)};function Sa(a,b){for(var c in a)b.call(i,a[c],c,a)}function Ta(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}var Ua="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Va(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var e=0;e<Ua.length;e++)c=Ua[e],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var J=Array.prototype,Wa=J.indexOf?function(a,b,c){return J.indexOf.call(a,b,c)}:function(a,b,c){c=c==l?0:0>c?Math.max(0,a.length+c):c;if(A(a))return!A(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},K=J.forEach?function(a,b,c){J.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=A(a)?a.split(""):a,e=0;e<d;e++)e in f&&b.call(c,f[e],e,a)},Xa=J.filter?function(a,b,c){return J.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=[],e=0,h=A(a)?a.split(""):
a,k=0;k<d;k++)if(k in h){var m=h[k];b.call(c,m,k,a)&&(f[e++]=m)}return f},Ya=J.every?function(a,b,c){return J.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=A(a)?a.split(""):a,e=0;e<d;e++)if(e in f&&!b.call(c,f[e],e,a))return s;return j};function Za(a,b){return 0<=Wa(a,b)}function $a(a,b){var c=Wa(a,b);0<=c&&J.splice.call(a,c,1)}function ab(a,b,c,d){J.splice.apply(a,bb(arguments,1))}function bb(a,b,c){return 2>=arguments.length?J.slice.call(a,b):J.slice.call(a,b,c)};var cb="StopIteration"in y?y.StopIteration:Error("StopIteration");function db(){}db.prototype.next=function(){g(cb)};db.prototype.Qa=function(){return this};function eb(a){if(a instanceof db)return a;if("function"==typeof a.Qa)return a.Qa(s);if(ga(a)){var b=0,c=new db;c.next=function(){for(;;){b>=a.length&&g(cb);if(b in a)return a[b++];b++}};return c}g(Error("Not implemented"))};function fb(a,b){this.S={};this.f=[];var c=arguments.length;if(1<c){c%2&&g(Error("Uneven number of arguments"));for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){if(a instanceof fb){c=gb(a);hb(a);for(var d=[],f=0;f<a.f.length;f++)d.push(a.S[a.f[f]])}else{var c=Ta(a),f=[],e=0;for(d in a)f[e++]=a[d];d=f}for(f=0;f<c.length;f++)this.set(c[f],d[f])}}x=fb.prototype;x.k=0;x.version_=0;function gb(a){hb(a);return a.f.concat()}
function hb(a){if(a.k!=a.f.length){for(var b=0,c=0;b<a.f.length;){var d=a.f[b];Object.prototype.hasOwnProperty.call(a.S,d)&&(a.f[c++]=d);b++}a.f.length=c}if(a.k!=a.f.length){for(var f={},c=b=0;b<a.f.length;)d=a.f[b],Object.prototype.hasOwnProperty.call(f,d)||(a.f[c++]=d,f[d]=1),b++;a.f.length=c}}x.get=function(a,b){return Object.prototype.hasOwnProperty.call(this.S,a)?this.S[a]:b};
x.set=function(a,b){Object.prototype.hasOwnProperty.call(this.S,a)||(this.k++,this.f.push(a),this.version_++);this.S[a]=b};x.Qa=function(a){hb(this);var b=0,c=this.f,d=this.S,f=this.version_,e=this,h=new db;h.next=function(){for(;;){f!=e.version_&&g(Error("The map has changed since the iterator was created"));b>=c.length&&g(cb);var h=c[b++];return a?h:d[h]}};return h};function ib(){this.H=s}ib.prototype.F=function(){this.H||(this.H=j,this.g())};ib.prototype.g=function(){this.bc&&jb.apply(l,this.bc);if(this.Kb)for(;this.Kb.length;)this.Kb.shift()()};function jb(a){for(var b=0,c=arguments.length;b<c;++b){var d=arguments[b];ga(d)?jb.apply(l,d):d&&"function"==typeof d.F&&d.F()}};function kb(a,b){this.H=s;this.sc=b;this.Va=[];a>this.sc&&g(Error("[goog.structs.SimplePool] Initial cannot be greater than max"));for(var c=0;c<a;c++)this.Va.push(this.Ba())}C(kb,ib);x=kb.prototype;x.sb=l;x.vb=l;x.Ba=function(){return this.sb?this.sb():{}};x.ub=function(a){if(this.vb)this.vb(a);else if(ha(a))if(B(a.F))a.F();else for(var b in a)delete a[b]};x.g=function(){kb.a.g.call(this);for(var a=this.Va;a.length;)this.ub(a.pop());delete this.Va};function lb(){this.yb=[];this.Lb=new fb;this.Dc=this.Ec=this.Fc=this.xc=0;this.Nb=new fb;this.$b=this.Cc=0;this.gb=1;this.cc=new kb(0,4E3);this.cc.Ba=function(){return new mb};this.yc=new kb(0,50);this.yc.Ba=function(){return new nb};var a=this;this.Db=new kb(0,2E3);this.Db.Ba=function(){return String(a.gb++)};this.Db.ub=t();this.Ic=3}function nb(){this.Pb=this.time=this.count=0}
nb.prototype.toString=function(){var a=[];a.push(this.type," ",this.count," (",Math.round(10*this.time)/10," ms)");this.Pb&&a.push(" [VarAlloc = ",this.Pb,"]");return a.join("")};function mb(){}function ob(a,b,c,d){var f=[];-1==c?f.push("    "):f.push(qb(a.xb-c));f.push(" ",rb(a.xb-b));0==a.Ua?f.push(" Start        "):1==a.Ua?(f.push(" Done "),f.push(qb(a.Kc-a.startTime)," ms ")):f.push(" Comment      ");f.push(d,a);0<a.Bc&&f.push("[VarAlloc ",a.Bc,"] ");return f.join("")}
mb.prototype.toString=function(){return this.type==l?this.Zb:"["+this.type+"] "+this.Zb};
lb.prototype.toString=function(){for(var a=[],b=-1,c=[],d=0;d<this.yb.length;d++){var f=this.yb[d];1==f.Ua&&c.pop();a.push(" ",ob(f,this.xc,b,c.join("")));b=f.xb;a.push("\n");0==f.Ua&&c.push("|  ")}if(0!=this.Lb.k){var e=pa();a.push(" Unstopped timers:\n");d=this.Lb;b=function(b){a.push("  ",b," (",e-b.startTime," ms, started at ",rb(b.startTime),")\n")};if(ga(d))try{K(d,b,i)}catch(h){h!==cb&&g(h)}else{d=eb(d);try{for(;;)b.call(i,d.next())}catch(k){k!==cb&&g(k)}}}b=gb(this.Nb);for(d=0;d<b.length;d++)c=
this.Nb.get(b[d]),1<c.count&&a.push(" TOTAL ",c,"\n");a.push("Total tracers created ",this.Cc,"\n","Total comments created ",this.$b,"\n","Overhead start: ",this.Fc," ms\n","Overhead end: ",this.Ec," ms\n","Overhead comment: ",this.Dc," ms\n");return a.join("")};function qb(a){var a=Math.round(a),b="";1E3>a&&(b=" ");100>a&&(b="  ");10>a&&(b="   ");return b+a}function rb(a){a=Math.round(a);return String(100+a/1E3%60).substring(1,3)+"."+String(1E3+a%1E3).substring(1,4)}new lb;function sb(a){this.context=a;this.inputBuffer=this.context.createGainNode();this.outputBuffer=this.context.createGainNode();this.Sa=[];this.J=[]}x=sb.prototype;x.connect=function(a){this.next=a;this.Sa=[].concat(this.inputBuffer,this.J,this.outputBuffer,this.next);this.v()};x.G=u("inputBuffer");x.ta=u("outputBuffer");x.ha=aa("prev");x.v=function(){for(var a=this.Sa,b=0,c=a.length-1;b<c;b++)a[b].connect(a[b+1])};x.disconnect=function(){this.outputBuffer.disconnect()};function L(a){sb.call(this,a);this.ea=this.context.createGainNode();this.J.push(this.ea)}C(L,sb);L.prototype.p=function(a){a=Math.min(a,10);this.ea.gain.value=a/10};L.prototype.v=function(){for(var a=this.Sa,b=0,c=a.length-1;b<c;b++)a[b].connect(a[b+1]);this.va=[[this.J[0],this.inputBuffer,this.outputBuffer],[this.outputBuffer,this.J[this.J.length-1],l]]};function tb(a){L.call(this,a);this.na=this.context.createConvolver();this.qb=this.context.createGainNode();this.J=[this.na,this.qb];this.cb()}C(tb,L);tb.prototype.ab="audio/ir/speaker/AK-SPKRS_VinUs_002.wav";tb.prototype.v=function(){tb.a.v.call(this);this.inputBuffer.connect(this.outputBuffer)};tb.prototype.cb=function(){var a=this,b=new XMLHttpRequest;b.open("GET",this.ab,j);b.responseType="arraybuffer";b.onload=function(){a.context.decodeAudioData(b.response,function(b){a.na.buffer=b})};b.send()};var ub={},vb=s,wb="click mouseover mouseout mousemove mousedown mouseup mouseenter mouseleave scroll".split(" ");
function xb(a){var b,c=b=a.target,d;do{if(!(d=ub[c.getAttribute&&c.getAttribute("data-cmp")]))(d=ub[c.id])&&b.setAttribute("data-cmp",c.id);if(d)break}while(c=c.parentNode);c=(b=d)&&b.K&&b.K[a.type];"mouseover"==a.type?a.relatedTarget&&!yb(a.target,a.relatedTarget)&&(d=new M(a.A),d.type="mouseenter",xb(d)):"mouseout"==a.type&&(a.relatedTarget&&!yb(a.target,a.relatedTarget))&&(d=new M(a.A),d.type="mouseleave",xb(d));if(c){d=Ta(c);do if("mouseenter"==a.type||"mouseleave"==a.type){if(a.relatedTarget&&
!yb(a.target,a.relatedTarget)&&zb(b,a,c,d)===s)break}else if(zb(b,a,c,d)===s)break;while((a.target=a.target.parentNode)&&a.target!=b.e())}}function zb(a,b,c,d){var f=j;K(d,function(d){0<=Wa(Ab(d),b.target)&&(f=c[d].call(a,b))});return f};var Bb,Cb=document.createElement("div");Bb=function(a){Cb.innerHTML=a;return Cb.removeChild(Cb.firstChild)};function Db(a,b){this.x=a!==i?a:0;this.y=b!==i?b:0}Db.prototype.toString=function(){return"("+this.x+", "+this.y+")"};var Eb;function Fb(a){a=a.className;return A(a)&&a.match(/\S+/g)||[]}function Gb(a,b){for(var c=Fb(a),d=bb(arguments,1),f=c.length+d.length,e=c,h=0;h<d.length;h++)Za(e,d[h])||e.push(d[h]);a.className=c.join(" ");return c.length==f}function Hb(a,b){var c=Fb(a),d=bb(arguments,1),f,e=d;f=Xa(c,function(a){return!Za(e,a)});a.className=f.join(" ");return f.length==c.length-d.length};var Ib=!E||Ra(9),Jb=!F&&!E||E&&Ra(9)||F&&I("1.9.1");E&&I("9");function Kb(a){return a?new Lb(Mb(a)):Eb||(Eb=new Lb)}var Nb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function yb(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}function Mb(a){return 9==a.nodeType?a:a.ownerDocument||a.document}function Ob(a){var b=a.getAttributeNode("tabindex");return b&&b.specified?(a=a.tabIndex,"number"==typeof a&&0<=a&&32768>a):s}function Lb(a){this.I=a||y.document||document}x=Lb.prototype;x.Wa=Kb;
x.e=function(a){return A(a)?this.I.getElementById(a):a};x.Y=Lb.prototype.e;
x.z=function(a,b,c){var d=this.I,f=arguments,e=f[0],h=f[1];if(!Ib&&h&&(h.name||h.type)){e=["<",e];h.name&&e.push(' name="',ra(h.name),'"');if(h.type){e.push(' type="',ra(h.type),'"');var k={};Va(k,h);h=k}e.push(">");e=e.join("")}e=d.createElement(e);if(h)if(A(h))e.className=h;else if("array"==ea(h))Gb.apply(l,[e].concat(h));else{var m=e;Sa(h,function(a,b){"style"==b?m.style.cssText=a:"class"==b?m.className=a:"for"==b?m.htmlFor=a:b in Nb?m.setAttribute(Nb[b],a):0==b.lastIndexOf("aria-",0)||0==b.lastIndexOf("data-",
0)?m.setAttribute(b,a):m[b]=a})}if(2<f.length)for(var n=d,p=e,d=f,f=function(a){a&&p.appendChild(A(a)?n.createTextNode(a):a)},h=2;h<d.length;h++){var q=d[h];if(ga(q)&&!(ha(q)&&0<q.nodeType)){var k=K,r;a:{if((r=q)&&"number"==typeof r.length){if(ha(r)){r="function"==typeof r.item||"string"==typeof r.item;break a}if(B(r)){r="function"==typeof r.item;break a}}r=s}if(r)if(r=q.length,0<r){for(var z=Array(r),v=0;v<r;v++)z[v]=q[v];q=z}else q=[];k(q,f)}else f(q)}return e};x.createElement=function(a){return this.I.createElement(a)};
x.createTextNode=function(a){return this.I.createTextNode(a)};x.appendChild=function(a,b){a.appendChild(b)};x.Da=function(a){return Jb&&a.children!=i?a.children:Xa(a.childNodes,function(a){return 1==a.nodeType})};x.contains=yb;function Pb(a,b){var c;a:{c=Mb(a);if(c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,l))){c=c[b]||c.getPropertyValue(b)||"";break a}c=""}return c||(a.currentStyle?a.currentStyle[b]:l)||a.style&&a.style[b]}
function Qb(a){if(E&&!Ra(8))return a.offsetParent;for(var b=Mb(a),c=Pb(a,"position"),d="fixed"==c||"absolute"==c,a=a.parentNode;a&&a!=b;a=a.parentNode)if(c=Pb(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return l}
function Rb(a){var b,c=Mb(a),d=Pb(a,"position"),f=F&&c.getBoxObjectFor&&!a.getBoundingClientRect&&"absolute"==d&&(b=c.getBoxObjectFor(a))&&(0>b.screenX||0>b.screenY),e=new Db(0,0),h;b=c?Mb(c):document;if(h=E)if(h=!Ra(9))h="CSS1Compat"!=Kb(b).I.compatMode;h=h?b.body:b.documentElement;if(a==h)return e;a:{if(Fa&&H&&(b=a.ownerDocument.defaultView,b!=b.top)){b=s;break a}b=!!a.getBoundingClientRect}if(b)d=a.getBoundingClientRect(),E&&(a=a.ownerDocument,d.left-=a.documentElement.clientLeft+a.body.clientLeft,
d.top-=a.documentElement.clientTop+a.body.clientTop),b=d,a=Kb(c).I,c=!H&&"CSS1Compat"==a.compatMode?a.documentElement:a.body,a=a.parentWindow||a.defaultView,c=new Db(a.pageXOffset||c.scrollLeft,a.pageYOffset||c.scrollTop),e.x=b.left+c.x,e.y=b.top+c.y;else if(c.getBoxObjectFor&&!f)b=c.getBoxObjectFor(a),c=c.getBoxObjectFor(h),e.x=b.screenX-c.screenX,e.y=b.screenY-c.screenY;else{b=a;do{e.x+=b.offsetLeft;e.y+=b.offsetTop;b!=a&&(e.x+=b.clientLeft||0,e.y+=b.clientTop||0);if(H&&"fixed"==Pb(b,"position")){e.x+=
c.body.scrollLeft;e.y+=c.body.scrollTop;break}b=b.offsetParent}while(b&&b!=a);if(D||H&&"absolute"==d)e.y-=c.body.offsetTop;for(b=a;(b=Qb(b))&&b!=c.body&&b!=h;)if(e.x-=b.scrollLeft,!D||"TR"!=b.tagName)e.y-=b.scrollTop}return e}var Sb=F?"MozUserSelect":H?"WebkitUserSelect":l;function Tb(){}var Ub=0;x=Tb.prototype;x.key=0;x.ga=s;x.ob=s;x.ua=function(a,b,c,d,f,e){B(a)?this.Gb=j:a&&a.handleEvent&&B(a.handleEvent)?this.Gb=s:g(Error("Invalid listener argument"));this.listener=a;this.proxy=b;this.src=c;this.type=d;this.capture=!!f;this.Za=e;this.ob=s;this.key=++Ub;this.ga=s};x.handleEvent=function(a){return this.Gb?this.listener.call(this.Za||this.src,a):this.listener.handleEvent.call(this.listener,a)};var Vb=!E||Ra(9),Wb=!E||Ra(9),Xb=E&&!I("8");!H||I("528");F&&I("1.9b")||E&&I("8")||D&&I("9.5")||H&&I("528");F&&!I("8")||E&&I("9");function Yb(a,b){this.type=a;this.currentTarget=this.target=b}x=Yb.prototype;x.g=t();x.F=t();x.T=s;x.defaultPrevented=s;x.Na=j;x.stopPropagation=function(){this.T=j};x.preventDefault=function(){this.defaultPrevented=j;this.Na=s};function Zb(a){Zb[" "](a);return a}Zb[" "]=ca;function M(a,b){a&&this.ua(a,b)}C(M,Yb);var $b=[1,4,2];x=M.prototype;x.target=l;x.relatedTarget=l;x.offsetX=0;x.offsetY=0;x.clientX=0;x.clientY=0;x.screenX=0;x.screenY=0;x.button=0;x.keyCode=0;x.charCode=0;x.ctrlKey=s;x.altKey=s;x.shiftKey=s;x.metaKey=s;x.hb=s;x.A=l;
x.ua=function(a,b){var c=this.type=a.type;Yb.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(F){var f;a:{try{Zb(d.nodeName);f=j;break a}catch(e){}f=s}f||(d=l)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=H||a.offsetX!==i?a.offsetX:a.layerX;this.offsetY=H||a.offsetY!==i?a.offsetY:a.layerY;this.clientX=a.clientX!==i?a.clientX:a.pageX;this.clientY=a.clientY!==i?a.clientY:a.pageY;this.screenX=a.screenX||
0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.hb=Ha?a.metaKey:a.ctrlKey;this.state=a.state;this.A=a;a.defaultPrevented&&this.preventDefault();delete this.T};function ac(a){return Vb?0==a.A.button:"click"==a.type?j:!!(a.A.button&$b[0])}
x.stopPropagation=function(){M.a.stopPropagation.call(this);this.A.stopPropagation?this.A.stopPropagation():this.A.cancelBubble=j};x.preventDefault=function(){M.a.preventDefault.call(this);var a=this.A;if(a.preventDefault)a.preventDefault();else if(a.returnValue=s,Xb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};x.g=t();var bc={},N={},O={},cc={};
function P(a,b,c,d,f){if(b){if("array"==ea(b)){for(var e=0;e<b.length;e++)P(a,b[e],c,d,f);return l}var d=!!d,h=N;b in h||(h[b]={k:0,t:0});h=h[b];d in h||(h[d]={k:0,t:0},h.k++);var h=h[d],k=ia(a),m;h.t++;if(h[k]){m=h[k];for(e=0;e<m.length;e++)if(h=m[e],h.listener==c&&h.Za==f){if(h.ga)break;return m[e].key}}else m=h[k]=[],h.k++;var n=dc,p=Wb?function(a){return n.call(p.src,p.key,a)}:function(a){a=n.call(p.src,p.key,a);if(!a)return a},e=p;e.src=a;h=new Tb;h.ua(c,e,a,b,d,f);c=h.key;e.key=c;m.push(h);
bc[c]=h;O[k]||(O[k]=[]);O[k].push(h);a.addEventListener?(a==y||!a.tb)&&a.addEventListener(b,e,d):a.attachEvent(b in cc?cc[b]:cc[b]="on"+b,e);return c}g(Error("Invalid event type"))}function ec(a,b,c,d,f){if("array"==ea(b))for(var e=0;e<b.length;e++)ec(a,b[e],c,d,f);else{d=!!d;a:{e=N;if(b in e&&(e=e[b],d in e&&(e=e[d],a=ia(a),e[a]))){a=e[a];break a}a=l}if(a)for(e=0;e<a.length;e++)if(a[e].listener==c&&a[e].capture==d&&a[e].Za==f){Q(a[e].key);break}}}
function Q(a){if(!bc[a])return s;var b=bc[a];if(b.ga)return s;var c=b.src,d=b.type,f=b.proxy,e=b.capture;c.removeEventListener?(c==y||!c.tb)&&c.removeEventListener(d,f,e):c.detachEvent&&c.detachEvent(d in cc?cc[d]:cc[d]="on"+d,f);c=ia(c);O[c]&&(f=O[c],$a(f,b),0==f.length&&delete O[c]);b.ga=j;if(b=N[d][e][c])b.Ib=j,fc(d,e,c,b);delete bc[a];return j}
function fc(a,b,c,d){if(!d.Ga&&d.Ib){for(var f=0,e=0;f<d.length;f++)d[f].ga?d[f].proxy.src=l:(f!=e&&(d[e]=d[f]),e++);d.length=e;d.Ib=s;0==e&&(delete N[a][b][c],N[a][b].k--,0==N[a][b].k&&(delete N[a][b],N[a].k--),0==N[a].k&&delete N[a])}}function gc(a,b,c,d,f){var e=1,b=ia(b);if(a[b]){a.t--;a=a[b];a.Ga?a.Ga++:a.Ga=1;try{for(var h=a.length,k=0;k<h;k++){var m=a[k];m&&!m.ga&&(e&=hc(m,f)!==s)}}finally{a.Ga--,fc(c,d,b,a)}}return Boolean(e)}function hc(a,b){a.ob&&Q(a.key);return a.handleEvent(b)}
function dc(a,b){if(!bc[a])return j;var c=bc[a],d=c.type,f=N;if(!(d in f))return j;var f=f[d],e,h;if(!Wb){var k;if(!(k=b))a:{k=["window","event"];for(var m=y;e=k.shift();)if(m[e]!=l)m=m[e];else{k=l;break a}k=m}e=k;k=j in f;m=s in f;if(k){if(0>e.keyCode||e.returnValue!=i)return j;a:{var n=s;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(p){n=j}if(n||e.returnValue==i)e.returnValue=j}}n=new M;n.ua(e,this);e=j;try{if(k){for(var q=[],r=n.currentTarget;r;r=r.parentNode)q.push(r);h=f[j];h.t=h.k;for(var z=
q.length-1;!n.T&&0<=z&&h.t;z--)n.currentTarget=q[z],e&=gc(h,q[z],d,j,n);if(m){h=f[s];h.t=h.k;for(z=0;!n.T&&z<q.length&&h.t;z++)n.currentTarget=q[z],e&=gc(h,q[z],d,s,n)}}else e=hc(c,n)}finally{q&&(q.length=0)}return e}d=new M(b,this);return e=hc(c,d)};function ic(a){this.H=s;this.nc=a;this.f=[]}C(ic,ib);var jc=[];function R(a,b,c,d){"array"!=ea(c)&&(jc[0]=c,c=jc);for(var f=0;f<c.length;f++){var e=P(b,c[f],d||a,s,a.nc||a);a.f.push(e)}return a}ic.prototype.g=function(){ic.a.g.call(this);K(this.f,Q);this.f.length=0};ic.prototype.handleEvent=function(){g(Error("EventHandler.handleEvent not implemented"))};function kc(){}da(kc);kc.prototype.gb=0;kc.sa();function lc(){this.H=s}C(lc,ib);x=lc.prototype;x.tb=j;x.Ma=l;x.kb=aa("Ma");x.addEventListener=function(a,b,c,d){P(this,a,b,c,d)};x.removeEventListener=function(a,b,c,d){ec(this,a,b,c,d)};
x.dispatchEvent=function(a){var b=a.type||a,c=N;if(b in c){if(A(a))a=new Yb(a,this);else if(a instanceof Yb)a.target=a.target||this;else{var d=a,a=new Yb(b,this);Va(a,d)}var d=1,f,c=c[b],b=j in c,e;if(b){f=[];for(e=this;e;e=e.Ma)f.push(e);e=c[j];e.t=e.k;for(var h=f.length-1;!a.T&&0<=h&&e.t;h--)a.currentTarget=f[h],d&=gc(e,f[h],a.type,j,a)&&a.Na!=s}if(s in c)if(e=c[s],e.t=e.k,b)for(h=0;!a.T&&h<f.length&&e.t;h++)a.currentTarget=f[h],d&=gc(e,f[h],a.type,s,a)&&a.Na!=s;else for(f=this;!a.T&&f&&e.t;f=f.Ma)a.currentTarget=
f,d&=gc(e,f,a.type,s,a)&&a.Na!=s;a=Boolean(d)}else a=j;return a};x.g=function(){lc.a.g.call(this);var a,b=0,c=a==l;a=!!a;if(this==l)Sa(O,function(d){for(var f=d.length-1;0<=f;f--){var e=d[f];if(c||a==e.capture)Q(e.key),b++}});else{var d=ia(this);if(O[d])for(var d=O[d],f=d.length-1;0<=f;f--){var e=d[f];if(c||a==e.capture)Q(e.key),b++}}this.Ma=l};function S(a){this.H=s;this.Ca=a||Kb();this.xa=mc}C(S,lc);S.prototype.oc=kc.sa();var mc=l;function nc(a,b){switch(a){case 1:return b?"disable":"enable";case 2:return b?"highlight":"unhighlight";case 4:return b?"activate":"deactivate";case 8:return b?"select":"unselect";case 16:return b?"check":"uncheck";case 32:return b?"focus":"blur";case 64:return b?"open":"close"}g(Error("Invalid component state"))}x=S.prototype;x.ca=l;x.h=s;x.d=l;x.xa=l;x.fb=l;x.s=l;x.j=l;x.l=l;x.Gc=s;
function T(a){return a.ca||(a.ca=":"+(a.oc.gb++).toString(36))}x.e=u("d");function oc(a,b){a==b&&g(Error("Unable to set parent component"));b&&(a.s&&a.ca&&a.s.l&&a.ca&&(a.ca in a.s.l&&a.s.l[a.ca])&&a.s!=b)&&g(Error("Unable to set parent component"));a.s=b;S.a.kb.call(a,b)}x.getParent=u("s");x.kb=function(a){this.s&&this.s!=a&&g(Error("Method not supported"));S.a.kb.call(this,a)};x.Wa=u("Ca");x.z=function(){this.d=this.Ca.createElement("div")};
function pc(a,b,c){a.h&&g(Error("Component already rendered"));a.d||a.z();b?b.insertBefore(a.d,c||l):a.Ca.I.body.appendChild(a.d);(!a.s||a.s.h)&&a.m()}x.m=function(){this.h=j;qc(this,function(a){!a.h&&a.e()&&a.m()})};x.qa=function(){qc(this,function(a){a.h&&a.qa()});if(this.L){var a=this.L;K(a.f,Q);a.f.length=0}this.h=s};
x.g=function(){S.a.g.call(this);this.h&&this.qa();this.L&&(this.L.F(),delete this.L);qc(this,function(a){a.F()});if(!this.Gc&&this.d){var a=this.d;a&&a.parentNode&&a.parentNode.removeChild(a)}this.s=this.fb=this.d=this.l=this.j=l};x.Oa=aa("fb");
x.Z=function(a,b,c){a.h&&(c||!this.h)&&g(Error("Component already rendered"));(0>b||b>(this.j?this.j.length:0))&&g(Error("Child component index out of bounds"));if(!this.l||!this.j)this.l={},this.j=[];if(a.getParent()==this){var d=T(a);this.l[d]=a;$a(this.j,a)}else{var d=this.l,f=T(a);f in d&&g(Error('The object already contains the key "'+f+'"'));d[f]=a}oc(a,this);ab(this.j,b,0,a);a.h&&this.h&&a.getParent()==this?(c=this.ra(),c.insertBefore(a.e(),c.childNodes[b]||l)):c?(this.d||this.z(),b=this.j?
this.j[b+1]||l:l,pc(a,this.ra(),b?b.d:l)):this.h&&(!a.h&&a.d&&a.d.parentNode)&&a.m()};x.ra=u("d");x.ya=function(a){this.h&&g(Error("Component already rendered"));this.xa=a};function qc(a,b){a.j&&K(a.j,b,i)}x.removeChild=function(a,b){if(a){var c=A(a)?a:T(a),a=this.l&&c?(c in this.l?this.l[c]:i)||l:l;if(c&&a){var d=this.l;c in d&&delete d[c];$a(this.j,a);b&&(a.qa(),a.d&&(c=a.d)&&c.parentNode&&c.parentNode.removeChild(c));oc(a,l)}}a||g(Error("Child is not in parent component"));return a};function rc(){}var sc;da(rc);x=rc.prototype;x.z=function(a){var b=a.Wa().z("div",tc(this,a).join(" "),a.Ta);a.isEnabled()||uc(b,1,j);a.i&8&&uc(b,8,j);a.w&16&&uc(b,16,!!(a.i&16));a.w&64&&uc(b,64,!!(a.i&64));return b};x.ra=function(a){return a};x.pa=function(a,b,c){if(a=a.e?a.e():a)if(E&&!I("7")){var d=vc(Fb(a),b);d.push(b);oa(c?Gb:Hb,a).apply(l,d)}else c?Gb(a,b):Hb(a,b)};
x.ib=function(a,b){var c=!b,d=E||D?a.getElementsByTagName("*"):l;if(Sb){if(c=c?"none":"",a.style[Sb]=c,d)for(var f=0,e;e=d[f];f++)e.style[Sb]=c}else if(E||D)if(c=c?"on":"",a.setAttribute("unselectable",c),d)for(f=0;e=d[f];f++)e.setAttribute("unselectable",c)};x.ya=function(a,b){this.pa(a,this.aa()+"-rtl",b)};function wc(a,b){var c;if(a.w&32&&(c=a.ba())){if(!b&&a.i&32){try{c.blur()}catch(d){}a.i&32&&a.Bb()}Ob(c)!=b&&(b?c.tabIndex=0:(c.tabIndex=-1,c.removeAttribute("tabIndex")))}}
x.lb=function(a,b){a.style.display=b?"":"none"};x.C=function(a,b,c){var d=a.e();if(d){var f=xc(this,b);f&&this.pa(a,f,c);uc(d,b,c)}};function uc(a,b,c){sc||(sc={1:"disabled",8:"selected",16:"checked",64:"expanded"});(b=sc[b])&&a.setAttribute("aria-"+b,c)}x.ba=function(a){return a.e()};x.aa=function(){return"goog-control"};
function tc(a,b){var c=a.aa(),d=[c],f=a.aa();f!=c&&d.push(f);c=b.R();for(f=[];c;){var e=c&-c;f.push(xc(a,e));c&=~e}d.push.apply(d,f);(c=b.B)&&d.push.apply(d,c);E&&!I("7")&&d.push.apply(d,vc(d));return d}function vc(a,b){var c=[];b&&(a=a.concat([b]));K([],function(d){Ya(d,oa(Za,a))&&(!b||Za(d,b))&&c.push(d.join("_"))});return c}function xc(a,b){if(!a.pb){var c=a.aa();a.pb={1:c+"-disabled",2:c+"-hover",4:c+"-active",8:c+"-selected",16:c+"-checked",32:c+"-focused",64:c+"-open"}}return a.pb[b]};function yc(a,b){a||g(Error("Invalid class name "+a));B(b)||g(Error("Invalid decorator function "+b))}var zc={};function Ac(a,b,c,d,f){if(!E&&(!H||!I("525")))return j;if(Ha&&f)return Bc(a);if(f&&!d||!c&&(17==b||18==b)||E&&d&&b==a)return s;switch(a){case 13:return!(E&&Ra(9));case 27:return!H}return Bc(a)}function Bc(a){if(48<=a&&57>=a||96<=a&&106>=a||65<=a&&90>=a||H&&0==a)return j;switch(a){case 32:case 63:case 107:case 109:case 110:case 111:case 186:case 59:case 189:case 187:case 61:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return j;default:return s}}
function Cc(a){switch(a){case 61:return 187;case 59:return 186;case 224:return 91;case 0:return 224;default:return a}};function Dc(a,b){this.H=s;a&&Ec(this,a,b)}C(Dc,lc);x=Dc.prototype;x.d=l;x.Ea=l;x.bb=l;x.Fa=l;x.N=-1;x.M=-1;
var Fc={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},Gc={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},Hc=E||H&&I("525");x=Dc.prototype;
x.fc=function(a){if(H&&(17==this.N&&!a.ctrlKey||18==this.N&&!a.altKey))this.M=this.N=-1;Hc&&!Ac(a.keyCode,this.N,a.shiftKey,a.ctrlKey,a.altKey)?this.handleEvent(a):this.M=F?Cc(a.keyCode):a.keyCode};x.hc=function(){this.M=this.N=-1};
x.handleEvent=function(a){var b=a.A,c,d;E&&"keypress"==a.type?(c=this.M,d=13!=c&&27!=c?b.keyCode:0):H&&"keypress"==a.type?(c=this.M,d=0<=b.charCode&&63232>b.charCode&&Bc(c)?b.charCode:0):D?(c=this.M,d=Bc(c)?b.keyCode:0):(c=b.keyCode||this.M,d=b.charCode||0,Ha&&(63==d&&224==c)&&(c=191));var f=c,e=b.keyIdentifier;c?63232<=c&&c in Fc?f=Fc[c]:25==c&&a.shiftKey&&(f=9):e&&e in Gc&&(f=Gc[e]);a=f==this.N;this.N=f;b=new Ic(f,d,a,b);this.dispatchEvent(b)};x.e=u("d");
function Ec(a,b,c){a.Fa&&a.detach();a.d=b;a.Ea=P(a.d,"keypress",a,c);a.bb=P(a.d,"keydown",a.fc,c,a);a.Fa=P(a.d,"keyup",a.hc,c,a)}x.detach=function(){this.Ea&&(Q(this.Ea),Q(this.bb),Q(this.Fa),this.Fa=this.bb=this.Ea=l);this.d=l;this.M=this.N=-1};x.g=function(){Dc.a.g.call(this);this.detach()};function Ic(a,b,c,d){d&&this.ua(d,i);this.type="key";this.keyCode=a;this.charCode=b;this.repeat=c}C(Ic,M);function U(a,b,c){S.call(this,c);if(!b){for(var b=this.constructor,d;b;){d=ia(b);if(d=zc[d])break;b=b.a?b.a.constructor:l}b=d?B(d.sa)?d.sa():new d:l}this.r=b;this.Ta=a}C(U,S);x=U.prototype;x.Ta=l;x.i=0;x.w=39;x.Xb=255;x.zc=0;x.ja=j;x.B=l;x.jc=j;x.Ra=s;x.vc=l;x.ba=function(){return this.r.ba(this)};x.pa=function(a,b){b?a&&(this.B?Za(this.B,a)||this.B.push(a):this.B=[a],this.r.pa(this,a,j)):a&&this.B&&($a(this.B,a),0==this.B.length&&(this.B=l),this.r.pa(this,a,s))};
x.z=function(){var a=this.r.z(this);this.d=a;var b=this.vc||i;b&&a.setAttribute("role",b);this.Ra||this.r.ib(a,s);this.ja||this.r.lb(a,s)};x.ra=function(){return this.r.ra(this.e())};
x.m=function(){U.a.m.call(this);var a=this.r;this.xa==l&&(this.xa="rtl"==Pb(this.h?this.d:this.Ca.I.body,"direction"));this.xa&&a.ya(this.e(),j);this.isEnabled()&&wc(this,this.ja);if(this.w&-2){if(this.jc){var a=this.L||(this.L=new ic(this)),b=this.e();R(R(R(R(a,b,"mouseover",this.lc),b,"mousedown",this.ic),b,"mouseup",this.mc),b,"mouseout",this.kc);this.Cb!=ca&&R(a,b,"contextmenu",this.Cb);E&&R(a,b,"dblclick",this.dc)}if(this.w&32&&(a=this.ba()))b=this.da||(this.da=new Dc),Ec(b,a),R(R(R(this.L||
(this.L=new ic(this)),b,"key",this.gc),a,"focus",this.ec),a,"blur",this.Bb)}};x.qa=function(){U.a.qa.call(this);this.da&&this.da.detach();this.ja&&this.isEnabled()&&wc(this,s)};x.g=function(){U.a.g.call(this);this.da&&(this.da.F(),delete this.da);delete this.r;this.B=this.Ta=l};x.ya=function(a){U.a.ya.call(this,a);var b=this.e();b&&this.r.ya(b,a)};x.ib=function(a){this.Ra=a;var b=this.e();b&&this.r.ib(b,a)};
x.lb=function(a,b){if(b||this.ja!=a&&this.dispatchEvent(a?"show":"hide")){var c=this.e();c&&this.r.lb(c,a);this.isEnabled()&&wc(this,a);this.ja=a;return j}return s};x.isEnabled=function(){return!(this.i&1)};function Jc(a,b){Kc(a,2,b)&&a.C(2,b)}x.setActive=function(a){Kc(this,4,a)&&this.C(4,a)};x.R=u("i");x.C=function(a,b){this.w&a&&b!=!!(this.i&a)&&(this.r.C(this,a,b),this.i=b?this.i|a:this.i&~a)};function Lc(a,b){a.h&&a.i&b&&g(Error("Component already rendered"));a.i&b&&a.C(b,s);a.w&=~b}
function V(a,b){return!!(a.Xb&b)&&!!(a.w&b)}function Kc(a,b,c){return!!(a.w&b)&&!!(a.i&b)!=c&&(!(a.zc&b)||a.dispatchEvent(nc(b,c)))&&!a.H}x.lc=function(a){!Mc(a,this.e())&&(this.dispatchEvent("enter")&&this.isEnabled()&&V(this,2))&&Jc(this,j)};x.kc=function(a){!Mc(a,this.e())&&this.dispatchEvent("leave")&&(V(this,4)&&this.setActive(s),V(this,2)&&Jc(this,s))};x.Cb=ca;function Mc(a,b){return!!a.relatedTarget&&yb(b,a.relatedTarget)}
x.ic=function(a){if(this.isEnabled()&&(V(this,2)&&Jc(this,j),ac(a)&&(!H||!Ha||!a.ctrlKey))){V(this,4)&&this.setActive(j);var b;this.w&32&&(b=this.ba())&&Ob(b)&&this.ba().focus()}!this.Ra&&(ac(a)&&(!H||!Ha||!a.ctrlKey))&&a.preventDefault()};x.mc=function(a){this.isEnabled()&&(V(this,2)&&Jc(this,j),this.i&4&&(Nc(this,a)&&V(this,4))&&this.setActive(s))};x.dc=function(a){this.isEnabled()&&Nc(this,a)};
function Nc(a,b){if(V(a,16)){var c=!(a.i&16);Kc(a,16,c)&&a.C(16,c)}V(a,8)&&Kc(a,8,j)&&a.C(8,j);V(a,64)&&(c=!(a.i&64),Kc(a,64,c)&&a.C(64,c));c=new Yb("action",a);b&&(c.altKey=b.altKey,c.ctrlKey=b.ctrlKey,c.metaKey=b.metaKey,c.shiftKey=b.shiftKey,c.hb=b.hb);return a.dispatchEvent(c)}x.ec=function(){V(this,32)&&Kc(this,32,j)&&this.C(32,j)};x.Bb=function(){V(this,4)&&this.setActive(s);V(this,32)&&Kc(this,32,s)&&this.C(32,s)};
x.gc=function(a){return this.ja&&this.isEnabled()&&13==a.keyCode&&Nc(this,a)?(a.preventDefault(),a.stopPropagation(),j):s};B(U)||g(Error("Invalid component class "+U));B(rc)||g(Error("Invalid renderer class "+rc));var Oc=ia(U);zc[Oc]=rc;yc("goog-control",function(){return new U(l)});function Pc(){}C(Pc,rc);da(Pc);Pc.prototype.z=function(a){return a.Wa().z("div",this.aa())};Pc.prototype.aa=function(){return"goog-menuseparator"};function Qc(a,b){U.call(this,l,a||Pc.sa(),b);Lc(this,1);Lc(this,2);Lc(this,4);Lc(this,32);this.i=1}C(Qc,U);Qc.prototype.m=function(){Qc.a.m.call(this);this.e().setAttribute("role","separator")};yc("goog-menuseparator",function(){return new Qc});function W(){S.call(this);vb||(vb=j,P(window,"load",function(){P(document.body,wb,xb)}));ub[T(this)]=this}C(W,S);x=W.prototype;x.la=t();x.z=function(){this.d=Bb(this.X())};x.Oa=function(a){W.a.Oa.call(this,a);this.b=this.fb};x.Z=function(a,b,c){c!=s&&(c=j);W.a.Z.call(this,a,b,c)};x.Wb=function(a,b){var c=this;a.forEach(function(a){c.Z(a,c.j?c.j.length:0,b)},this)};x.Da=function(){var a=this,b=[];qc(this,function(a){b.push(T(a))});return b.map(function(b){return a.l&&b?(b in a.l?a.l[b]:i)||l:l})};
x.g=function(){W.a.g.call(this);this.b=l};x.Y=function(a){return Ab(a,this.e())};x.X=function(){return'<div id="'+T(this)+'"></div>'};function Rc(){}C(Rc,lc);function X(a,b,c){a instanceof Function?this.Yb=a:this.param=a;this.name=b;this.Ia=c;this.value=0}C(X,Rc);X.prototype.W=function(a){var b=this.value,a=Math.min(a,10),a=Math.max(a,0);this.Mb(a,b);a={type:Sc,newValue:this.value,oldValue:b};this.param?this.param.value=this.value:this.Yb(this.value,b);this.dispatchEvent(a)};X.prototype.Mb=function(a){this.value=a*this.Ia};X.prototype.Xa=function(){return this.value/this.Ia};var Sc="valueChanged";function Y(a,b,c,d){this.Oa(new this.o(a,b,c||1));this.size=d||Tc;this.la();this.W(10);W.call(this)}C(Y,W);x=Y.prototype;x.o=X;x.nb=26;x.W=function(a){this.b.W(a)};x.ia=function(){if(this.h){var a="rotateZ("+this.b.Xa()*this.nb+"deg)";this.Y(this.u.mb)[0].style["-webkit-transform"]=a}};x.X=function(){return'<div class="pot '+this.size+'" id="'+T(this)+'"><div class="knobHolder"><img class="knob" src="img/pot-small.png"/></div><div class="nameHolder"><div class="name">'+this.b.name+"</div></div></div>"};
x.m=function(){Y.a.m.call(this);this.ia()};x.u={mb:".knob",Sb:".knobHolder"};var Tc="regular";Y.prototype.la=function(){P(this.b,Sc,this.ia,s,this)};var Uc=Y.prototype;Uc.K={};(Uc.K.mousedown={})[Uc.u.mb]=function(a){this.zb=j;this.Jb=a.clientY;var b=P(document.body,"mouseup",function(){this.zb=s;Q(c);Q(b)},s,this),c=P(document.body,"mousemove",function(a){this.zb&&(this.W(this.b.Xa()-(a.clientY-this.Jb)*this.nb/360),this.Jb=a.clientY)},s,this)};function Vc(a,b,c){X.call(this,a,b,c)}C(Vc,X);function Wc(a,b,c,d){Y.call(this,a,b,c,d)}C(Wc,Y);Wc.prototype.o=Vc;var Xc={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",
darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",
ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",grey:"#808080",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};function Yc(a){var b={},a=String(a),c="#"==a.charAt(0)?a:"#"+a;if(Zc.test(c))return b.$a=$c(c),b.type="hex",b;a:{var d=a.match(ad);if(d){var c=Number(d[1]),f=Number(d[2]),d=Number(d[3]);if(0<=c&&255>=c&&0<=f&&255>=f&&0<=d&&255>=d){c=[c,f,d];break a}}c=[]}if(c.length)return f=c[0],a=c[1],c=c[2],f=Number(f),a=Number(a),c=Number(c),(isNaN(f)||0>f||255<f||isNaN(a)||0>a||255<a||isNaN(c)||0>c||255<c)&&g(Error('"('+f+","+a+","+c+'") is not a valid RGB color')),f=bd(f.toString(16)),a=bd(a.toString(16)),c=
bd(c.toString(16)),b.$a="#"+f+a+c,b.type="rgb",b;if(Xc&&(c=Xc[a.toLowerCase()]))return b.$a=c,b.type="named",b;g(Error(a+" is not a valid color string"))}var cd=/#(.)(.)(.)/;function $c(a){Zc.test(a)||g(Error("'"+a+"' is not a valid hex color"));4==a.length&&(a=a.replace(cd,"#$1$1$2$2$3$3"));return a.toLowerCase()}var Zc=/^#(?:[0-9a-f]{3}){1,2}$/i,ad=/^(?:rgb)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\)$/i;function bd(a){return 1==a.length?"0"+a:a};function dd(a,b,c){function d(a,b,c,d,f){return a+"px "+b+"px "+c+"px "+((f||0)+"px")+" hsl("+m[0]+", "+100*m[1]+"%, "+d+"%)"}var f,e,h=0.5;f=f||[];e=e||[];var k=document.defaultView.getComputedStyle(a,l).getPropertyValue("background-color"),m,n,k=Yc(k).$a,k=$c(k);n=[parseInt(k.substr(1,2),16),parseInt(k.substr(3,2),16),parseInt(k.substr(5,2),16)];var k=n[0]/255,p=n[1]/255;n=n[2]/255;var q=Math.max(k,p,n),r=Math.min(k,p,n),z=0,v=0,fa=0.5*(q+r);q!=r&&(q==k?z=60*(p-n)/(q-r):q==p?z=60*(n-k)/(q-r)+120:
q==n&&(z=60*(k-p)/(q-r)+240),v=0<fa&&0.5>=fa?(q-r)/(2*fa):(q-r)/(2-2*fa));m=[Math.round(z+360)%360,v,fa];m[2]*=h||1;h=[];k=(window.innerWidth/2-Rb(a).x-a.offsetWidth/2)/30;p=(window.innerHeight-Rb(a).y-a.offsetHeight/2)/80*b/10;for(n=b;b--;)h.push(d(k*b/n,2*p*b/n,0,100*m[2]-100*m[2]*(b+5)/n/1.6));h.splice(0,0,d(k,2*p,4*n,0,0),d(k/c/8,3*p,4*n,30,n/12),d(k/c/8,2*p,n,0,n/4/c),d(k/c/8,2.55*p,2*n,5,n/3/c));h=[].concat(f,h.reverse(),e);a.style.boxShadow=h.join(", ");a.style.left="-"+k/2+"px"};function ed(a){this.name=a;this.va=[[],[],[]];this.state=s}C(ed,Rc);ed.prototype.toggle=function(){var a=this.state;if(this.state=!this.state){var b=function(a){a[1].disconnect();a[0]&&a[1].connect(a[0])};K(this.va,function(a){a&&(b(a),setTimeout(function(){b(a)},10))})}else{var c=function(a){a[1].disconnect();a[2]&&a[1].connect(a[2])};K(this.va,function(a){c(a);setTimeout(function(){c(a)},10)})}this.dispatchEvent({type:this.state?fd:gd,newValue:this.state,oldValue:a})};
ed.prototype.jb=function(a){this.va=a;this.state=!this.state;this.toggle()};var fd="on",gd="off";function hd(a){this.b=new this.o(a);W.call(this)}C(hd,W);x=hd.prototype;x.o=ed;x.jb=function(a){this.b.jb(a)};x.R=function(){return this.b.state};x.toggle=function(){this.b.toggle()};x.X=function(){return'<div class="switch" id="'+T(this)+'"><img class="button" src="img/switch.png"/>'+(this.b.name?'<div class="name">'+this.b.name+"</div>":"")+"</div>"};x.u={Pa:".button"};var id=hd.prototype;id.K={};(id.K.click={})[id.u.Pa]=id.toggle;function jd(a){ed.call(this,a);this.state=s}C(jd,ed);function kd(a){hd.call(this,a);this.state=s}C(kd,hd);kd.prototype.o=jd;var ld=kd.prototype;ld.K={};var md=ld.K.mousedown={},nd=ld.K.mouseup={};md[ld.u.Pa]=ld.toggle;nd[ld.u.Pa]=ld.toggle;function Z(a){W.call(this);this.Oa(new this.o(a));this.rb();this.la()}C(Z,W);x=Z.prototype;x.o=sb;x.rb=function(){this.Hc=[]};x.G=function(){return this.b.G()};x.ta=function(){return this.b.ta()};x.ha=function(a){this.b.ha(a.ta())};x.connect=function(a){a.ha(this);this.b.connect(a.G())};x.disconnect=function(){this.b.disconnect()};function od(a,b){W.call(this);this.Ab=a;this.name=b||"";this.state=s;this.la()}C(od,W);x=od.prototype;x.toggle=function(){this.state=!this.state;this.ia()};x.ia=function(){if(this.h){var a=this.e();this.state?Gb(a,"on"):Hb(a,"on")}};x.X=function(){return'<div class="led" id="'+T(this)+'"><div class="nameHolder"><div class="name">'+this.name+"</div></div></div>"};x.m=function(){od.a.m.call(this);this.ia()};x.la=function(){this.Ab&&P(this.Ab.b,[fd,gd],this.tc,s,this)};
x.tc=function(a){this.state=a.newValue;this.ia()};function pd(a){ed.call(this,a);this.state=j}C(pd,ed);function qd(a){hd.call(this,a)}C(qd,hd);qd.prototype.o=pd;function rd(a){Z.call(this,a)}C(rd,Z);x=rd.prototype;x.o=L;x.rb=function(){this.oa();this.n=new qd;this.pc=new od(this.n);this.qc=[this.pc];this.Ac=[this.n];var a=this;P(this.n.b,fd,function(){this.b.v();setTimeout(function(){a.b.v()},10)},s,this)};x.oa=function(){this.ka=new Wc(this.b.ea.gain,"volume",0.1);this.wa=[this.ka]};x.connect=function(a){rd.a.connect.call(this,a);this.n.jb(this.b.va)};x.p=function(a){this.ka.W(a)};
x.X=function(){return'<div id="'+T(this)+'" class="box '+this.name+'"><div class="pots"></div><div class="name">'+this.name+'</div><div class="leds"></div><div class="switches"></div></div>'};x.m=function(){rd.a.m.call(this);this.wa.forEach(function(a){var b=this.Y(this.u.Ub)[0];pc(a,b)},this);this.Ac.forEach(function(a){var b=this.Y(this.u.Vb)[0];pc(a,b)},this);this.qc.forEach(function(a){var b=this.Y(this.u.Tb)[0];pc(a,b)},this)};x.u={Ub:".pots",Vb:".switches",Tb:".leds"};x.name="pb";function sd(a){Z.call(this,a)}C(sd,rd);sd.prototype.o=tb;sd.prototype.name="convo";sd.prototype.oa=function(){this.ka=new Y(this.b.qb.gain,"effect",1);this.wa=[].concat(this.ka)};function td(a){L.call(this,a)}C(td,L);function ud(a){Z.call(this,a)}C(ud,rd);ud.prototype.o=td;ud.prototype.name="volume";function vd(a){L.call(this,a);this.rc=3E3;this.Ha=this.context.createBiquadFilter();this.Ha.type=0;this.Ha.frequency.value=this.rc;this.Qb=this.context.createWaveShaper();this.J=[this.Qb,this.Ha,this.ea]}C(vd,L);vd.prototype.O=function(a){this.Rb=new Float32Array(22050);for(var b=Math.PI/180,c=0;22050>c;c+=1){var d=2*c/22050-1;this.Rb[c]=20*((3+a)*d)*b/(Math.PI+a*Math.abs(d))}this.Qb.curve=this.Rb};vd.prototype.P=function(a){this.Ha.frequency.value=2E3+a};function wd(a,b,c){X.call(this,a,b,c)}C(wd,X);wd.prototype.Mb=function(a){a=Math.pow(a,3)/100;this.value=a*this.Ia};wd.prototype.Xa=function(){return Math.round(100*Math.pow(100*this.value/this.Ia,1/3))/100};function xd(a,b,c,d){Y.call(this,a,b,c,d)}C(xd,Y);xd.prototype.o=wd;function yd(a){Z.call(this,a)}C(yd,rd);x=yd.prototype;x.o=vd;x.oa=function(){yd.a.oa.call(this);var a=na(this.b.O,this.b),b=na(this.b.P,this.b);this.wb=new xd(a,"drive",200);this.Ob=new xd(b,"tone",600,"small");this.wa.push(this.wb,this.Ob)};x.O=function(a){this.wb.W(a)};x.P=function(a){this.Ob.W(a)};x.name="overdrive";var zd;zd=function(){return j};/*
 Portions of this code are from the Dojo Toolkit, received by
 The Closure Library Authors under the BSD license. All other code is
 Copyright 2005-2009 The Closure Library Authors. All Rights Reserved.

The "New" BSD License:

Copyright (c) 2005-2009, The Dojo Foundation
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.
 Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.
 Neither the name of the Dojo Foundation nor the names of its contributors
    may be used to endorse or promote products derived from this software
    without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
var Ab;function Ad(a,b){var c=b||[];a&&c.push(a);return c}var Bd=H&&"BackCompat"==document.compatMode,Cd=document.firstChild.children?"children":"childNodes",Dd=s;
function Ed(a){function b(){0<=n&&(w.id=c(n,v).replace(/\\/g,""),n=-1);if(0<=p){var a=p==v?l:c(p,v);0>">~+".indexOf(a)?w.q=a:w.Ka=a;p=-1}0<=m&&(w.D.push(c(m+1,v).replace(/\\/g,"")),m=-1)}function c(b,c){return qa(a.slice(b,c))}for(var a=0<=">~+".indexOf(a.slice(-1))?a+" * ":a+" ",d=[],f=-1,e=-1,h=-1,k=-1,m=-1,n=-1,p=-1,q="",r="",z,v=0,fa=a.length,w=l,G=l;q=r,r=a.charAt(v),v<fa;v++)if("\\"!=q)if(w||(z=v,w={fa:l,U:[],Aa:[],D:[],q:l,Ka:l,id:l,Ya:function(){return Dd?this.uc:this.q}},p=v),0<=f)if("]"==
r){G.attr?G.eb=c(h||f+1,v):G.attr=c(f+1,v);if((f=G.eb)&&('"'==f.charAt(0)||"'"==f.charAt(0)))G.eb=f.slice(1,-1);w.Aa.push(G);G=l;f=h=-1}else"="==r&&(h=0<="|~^$*".indexOf(q)?q:"",G.type=h+r,G.attr=c(f+1,v-h.length),h=v+1);else 0<=e?")"==r&&(0<=k&&(G.value=c(e+1,v)),k=e=-1):"#"==r?(b(),n=v+1):"."==r?(b(),m=v):":"==r?(b(),k=v):"["==r?(b(),f=v,G={}):"("==r?(0<=k&&(G={name:c(k+1,v),value:l},w.U.push(G)),e=v):" "==r&&q!=r&&(b(),0<=k&&w.U.push({name:c(k+1,v)}),w.Hb=w.U.length||w.Aa.length||w.D.length,w.Jc=
w.fa=c(z,v),w.uc=w.q=w.Ka?l:w.q||"*",w.q&&(w.q=w.q.toUpperCase()),d.length&&d[d.length-1].Ka&&(w.Eb=d.pop(),w.fa=w.Eb.fa+" "+w.fa),d.push(w),w=l);return d}function Fd(a,b){return!a?b:!b?a:function(){return a.apply(window,arguments)&&b.apply(window,arguments)}}function Gd(a){return 1==a.nodeType}function Hd(a,b){return!a?"":"class"==b?a.className||"":"for"==b?a.htmlFor||"":"style"==b?a.style.cssText||"":(Dd?a.getAttribute(b):a.getAttribute(b,2))||""}
var Id={"*=":function(a,b){return function(c){return 0<=Hd(c,a).indexOf(b)}},"^=":function(a,b){return function(c){return 0==Hd(c,a).indexOf(b)}},"$=":function(a,b){return function(c){c=" "+Hd(c,a);return c.lastIndexOf(b)==c.length-b.length}},"~=":function(a,b){var c=" "+b+" ";return function(b){return 0<=(" "+Hd(b,a)+" ").indexOf(c)}},"|=":function(a,b){b=" "+b;return function(c){c=" "+Hd(c,a);return c==b||0==c.indexOf(b+"-")}},"=":function(a,b){return function(c){return Hd(c,a)==b}}},Jd="undefined"==
typeof document.firstChild.nextElementSibling,Kd=!Jd?"nextElementSibling":"nextSibling",Ld=!Jd?"previousElementSibling":"previousSibling",Md=Jd?Gd:zd;function Nd(a){for(;a=a[Ld];)if(Md(a))return s;return j}function Od(a){for(;a=a[Kd];)if(Md(a))return s;return j}function Pd(a){var b=a.parentNode,c=0,d=b[Cd],f=a._i||-1,e=b._l||-1;if(!d)return-1;d=d.length;if(e==d&&0<=f&&0<=e)return f;b._l=d;f=-1;for(b=b.firstElementChild||b.firstChild;b;b=b[Kd])Md(b)&&(b._i=++c,a===b&&(f=c));return f}
function Qd(a){return!(Pd(a)%2)}function Rd(a){return Pd(a)%2}
var Td={checked:function(){return function(a){return a.checked||a.attributes.checked}},"first-child":function(){return Nd},"last-child":function(){return Od},"only-child":function(){return function(a){return!Nd(a)||!Od(a)?s:j}},empty:function(){return function(a){for(var b=a.childNodes,a=a.childNodes.length-1;0<=a;a--){var c=b[a].nodeType;if(1===c||3==c)return s}return j}},contains:function(a,b){var c=b.charAt(0);if('"'==c||"'"==c)b=b.slice(1,-1);return function(a){return 0<=a.innerHTML.indexOf(b)}},
not:function(a,b){var c=Ed(b)[0],d={$:1};"*"!=c.q&&(d.q=1);c.D.length||(d.D=1);var f=Sd(c,d);return function(a){return!f(a)}},"nth-child":function(a,b){if("odd"==b)return Rd;if("even"==b)return Qd;if(-1!=b.indexOf("n")){var c=b.split("n",2),d=c[0]?"-"==c[0]?-1:parseInt(c[0],10):1,f=c[1]?parseInt(c[1],10):0,e=0,h=-1;0<d?0>f?f=f%d&&d+f%d:0<f&&(f>=d&&(e=f-f%d),f%=d):0>d&&(d*=-1,0<f&&(h=f,f%=d));if(0<d)return function(a){a=Pd(a);return a>=e&&(0>h||a<=h)&&a%d==f};b=f}var k=parseInt(b,10);return function(a){return Pd(a)==
k}}},Ud=E?function(a){var b=a.toLowerCase();"class"==b&&(a="className");return function(c){return Dd?c.getAttribute(a):c[a]||c[b]}}:function(a){return function(b){return b&&b.getAttribute&&b.hasAttribute(a)}};
function Sd(a,b){if(!a)return zd;var b=b||{},c=l;b.$||(c=Fd(c,Gd));b.q||"*"!=a.q&&(c=Fd(c,function(b){return b&&b.tagName==a.Ya()}));b.D||K(a.D,function(a,b){var e=RegExp("(?:^|\\s)"+a+"(?:\\s|$)");c=Fd(c,function(a){return e.test(a.className)});c.count=b});b.U||K(a.U,function(a){var b=a.name;Td[b]&&(c=Fd(c,Td[b](b,a.value)))});b.Aa||K(a.Aa,function(a){var b,e=a.attr;a.type&&Id[a.type]?b=Id[a.type](e,a.eb):e.length&&(b=Ud(e));b&&(c=Fd(c,b))});b.id||a.id&&(c=Fd(c,function(b){return!!b&&b.id==a.id}));
c||"default"in b||(c=zd);return c}var Vd={};
function Wd(a){var b=Vd[a.fa];if(b)return b;var c=a.Eb,c=c?c.Ka:"",d=Sd(a,{$:1}),f="*"==a.q,e=document.getElementsByClassName;if(c)if(e={$:1},f&&(e.q=1),d=Sd(a,e),"+"==c)var h=d,b=function(a,b,c){for(;a=a[Kd];)if(!Jd||Gd(a)){(!c||Xd(a,c))&&h(a)&&b.push(a);break}return b};else if("~"==c)var k=d,b=function(a,b,c){for(a=a[Kd];a;){if(Md(a)){if(c&&!Xd(a,c))break;k(a)&&b.push(a)}a=a[Kd]}return b};else{if(">"==c)var m=d,m=m||zd,b=function(a,b,c){for(var d=0,f=a[Cd];a=f[d++];)Md(a)&&((!c||Xd(a,c))&&m(a,d))&&
b.push(a);return b}}else if(a.id)d=!a.Hb&&f?zd:Sd(a,{$:1,id:1}),b=function(b,c){var f=Kb(b).e(a.id),e;if(e=f&&d(f))if(!(e=9==b.nodeType)){for(e=f.parentNode;e&&e!=b;)e=e.parentNode;e=!!e}if(e)return Ad(f,c)};else if(e&&/\{\s*\[native code\]\s*\}/.test(String(e))&&a.D.length&&!Bd)var d=Sd(a,{$:1,D:1,id:1}),n=a.D.join(" "),b=function(a,b){for(var c=Ad(0,b),e,f=0,h=a.getElementsByClassName(n);e=h[f++];)d(e,a)&&c.push(e);return c};else!f&&!a.Hb?b=function(b,c){for(var d=Ad(0,c),e,f=0,h=b.getElementsByTagName(a.Ya());e=
h[f++];)d.push(e);return d}:(d=Sd(a,{$:1,q:1,id:1}),b=function(b,c){for(var e=Ad(0,c),f,h=0,k=b.getElementsByTagName(a.Ya());f=k[h++];)d(f,b)&&e.push(f);return e});return Vd[a.fa]=b}var Yd={},Zd={};function $d(a){var b=Ed(qa(a));if(1==b.length){var c=Wd(b[0]);return function(a){if(a=c(a,[]))a.Ja=j;return a}}return function(a){for(var a=Ad(a),c,e,h=b.length,k,m,n=0;n<h;n++){m=[];c=b[n];e=a.length-1;0<e&&(k={},m.Ja=j);e=Wd(c);for(var p=0;c=a[p];p++)e(c,m,k);if(!m.length)break;a=m}return m}}
var ae=!!document.querySelectorAll&&(!H||I("526"));
function be(a,b){if(ae){var c=Zd[a];if(c&&!b)return c}if(c=Yd[a])return c;var c=a.charAt(0),d=-1==a.indexOf(" ");0<=a.indexOf("#")&&d&&(b=j);if(ae&&!b&&-1==">~+".indexOf(c)&&(!E||-1==a.indexOf(":"))&&!(Bd&&0<=a.indexOf("."))&&-1==a.indexOf(":contains")&&-1==a.indexOf("|=")){var f=0<=">~+".indexOf(a.charAt(a.length-1))?a+" *":a;return Zd[a]=function(b){try{9==b.nodeType||d||g("");var c=b.querySelectorAll(f);E?c.ac=j:c.Ja=j;return c}catch(e){return be(a,j)(b)}}}var e=a.split(/\s*,\s*/);return Yd[a]=
2>e.length?$d(a):function(a){for(var b=0,c=[],d;d=e[b++];)c=c.concat($d(d)(a));return c}}var ce=0,de=E?function(a){return Dd?a.getAttribute("_uid")||a.setAttribute("_uid",++ce)||ce:a.uniqueID}:function(a){return a._uid||(a._uid=++ce)};function Xd(a,b){if(!b)return 1;var c=de(a);return!b[c]?b[c]=1:0}
function ee(a){if(a&&a.Ja)return a;var b=[];if(!a||!a.length)return b;a[0]&&b.push(a[0]);if(2>a.length)return b;ce++;if(E&&Dd){var c=ce+"";a[0].setAttribute("_zipIdx",c);for(var d=1,f;f=a[d];d++)a[d].getAttribute("_zipIdx")!=c&&b.push(f),f.setAttribute("_zipIdx",c)}else if(E&&a.ac)try{for(d=1;f=a[d];d++)Gd(f)&&b.push(f)}catch(e){}else{a[0]&&(a[0]._zipIdx=ce);for(d=1;f=a[d];d++)a[d]._zipIdx!=ce&&b.push(f),f._zipIdx=ce}return b}
function fe(a,b){if(!a)return[];if(a.constructor==Array)return a;if(!A(a))return[a];if(A(b)&&(b=A(b)?document.getElementById(b):b,!b))return[];var b=b||document,c=b.ownerDocument||b.documentElement;Dd=b.contentType&&"application/xml"==b.contentType||D&&(b.doctype||"[object XMLDocument]"==c.toString())||!!c&&(E?c.xml:b.xmlVersion||c.xmlVersion);return(c=be(a)(b))&&c.Ja?c:ee(c)}fe.U=Td;Ab=fe;ba("goog.dom.query",Ab);ba("goog.dom.query.pseudos",Ab.U);function ge(a){L.call(this,a);this.na=this.context.createConvolver();this.J=[this.na,this.ea];this.cb()}C(ge,L);ge.prototype.ab="audio/ir/reverb/pcm90cleanplate.wav";ge.prototype.v=function(){ge.a.v.call(this);this.inputBuffer.connect(this.outputBuffer)};ge.prototype.cb=function(){var a=this,b=new XMLHttpRequest;b.open("GET",this.ab,j);b.responseType="arraybuffer";b.onload=function(){a.context.decodeAudioData(b.response,function(b){a.na.buffer=b})};b.send()};function he(a){Z.call(this,a)}C(he,rd);he.prototype.o=ge;he.prototype.name="reverb";he.prototype.oa=function(){this.ka=new Y(this.b.ea.gain,"effect",0.1);this.wa=[].concat(this.ka)};function ie(a){Z.call(this,a);this.context=a}C(ie,Z);function je(a){a.Da().forEach(function(a){dd(a.e(),40,0.7);a.wa.forEach(function(a){dd(a.Y(a.u.Sb)[0],10,4)})})}x=ie.prototype;x.Z=function(a,b,c){ie.a.Z.call(this,a,b,c);this.v();this.h&&je(this)};x.m=function(){ie.a.m.call(this);je(this)};x.X=function(){return'<div id="'+T(this)+'" class="board"></div>'};x.connect=function(a){ie.a.connect.call(this,a);this.La=a;this.v()};
x.v=function(){var a=this.Da();a.length&&(a.forEach(function(b,c){b.disconnect();a[c+1]&&b.connect(a[c+1])}),this.G().disconnect(),this.G().connect(a[0].G()),a.length&&this.La&&a[a.length-1].connect(this.La))};x.g=function(){this.Da().forEach(function(a){a.g()});ie.a.g.call(this)};function ke(a){this.source=a.destination}x=ke.prototype;x.G=u("source");x.ha=aa("prev");x.connect=t();x.ta=t();x.disconnect=t();function le(a){this.source=a.createBufferSource();this.source.loop=j}C(le,lc);x=le.prototype;x.play=function(a){2!=this.source.playbackState&&this.source.noteOn(a||0)};x.stop=function(a){2==this.source.playbackState&&this.source.noteOff(a||0)};x.connect=function(a){a.ha(this);this.source.connect(a.G())};x.disconnect=function(){this.source.disconnect()};x.ta=u("source");x.ha=t();x.G=t();function me(a,b){le.call(this,a);var c=this,d=new XMLHttpRequest;d.open("GET",b,j);d.responseType="arraybuffer";d.onload=function(){a.decodeAudioData(d.response,function(a){c.source.buffer=a;c.dispatchEvent("loaded")})};d.send()}C(me,le);function ne(){W.call(this);this.context=new webkitAudioContext;this.input=new me(this.context,"audio/samples/sample1.mp3");this.La=new ke(this.context)}C(ne,W);ne.prototype.getContext=u("context");function oe(a){a.input.disconnect();a.input.connect(a.ma);a.ma.connect(a.La)}ne.prototype.play=function(a){this.input.disconnect();this.input=new me(this.context,a);oe(this);this.input.play()};ne.prototype.stop=function(){this.input.stop()};ne.prototype.X=function(){return'<div id="'+T(this)+'" class="stage"></div>'};ba("pb",function(){function a(){p[n-1]&&p[n-1]();e.za.play("audio/samples/sample"+n+".mp3")}function b(){k.innerHTML=h?"&#9724;":"&#9654;";m.forEach(function(a){a.className="sample"});m[n-1].className="sample on"}this.za=new ne;pc(this.za,document.getElementById("floor"));var c=this.za.getContext(),d=new ie(c),f=this.za;f.ma&&f.ma.F();f.ma=d;oe(f);f.Z(f.ma,f.j?f.j.length:0,i);this.c=new yd(c);this.V=new he(c);this.volume=new ud(c);this.wc=new sd(c);W.prototype.Wb.call(d,[this.c,this.V,this.volume,
this.wc]);this.c.O(8);this.c.P(4);this.c.p(6);this.volume.p(10);this.V.p(3);var e=this,h=s,k=document.getElementById("controlButton"),m=document.getElementsByClassName("sample"),n=1,m=Array.prototype.slice.call(m),p=[];k.addEventListener("click",function(){h=!h;b();e.za.stop();h&&a()},s);m.forEach(function(c){c.addEventListener("click",function(){n=Array.prototype.slice.call(c.parentNode.children).indexOf(c)+1;h=j;b();a()})});p.push(function(){!e.c.n.R()&&e.c.n.toggle();e.c.p(10);e.c.O(2);e.c.P(7);
e.V.p(10)});p.push(function(){!e.c.n.R()&&e.c.n.toggle();e.c.p(6);e.c.O(6);e.c.P(3);e.V.p(3)});p.push(function(){!e.c.n.R()&&e.c.n.toggle();e.c.p(6);e.c.O(10);e.c.P(5);e.V.p(10)});p.push(function(){e.c.n.R()&&e.c.n.toggle();e.c.p(10);e.c.O(0);e.c.P(10);e.V.p(10)});p.push(function(){!e.c.n.R()&&e.c.n.toggle();e.c.p(10);e.c.O(10);e.c.P(3);e.V.p(7)})});})()
